// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Item {
    "id": string;
    "kind": string;
    "label": string;
    "description"?: string;
    "target": string;
    "status": string;
    "selectedByDefault": boolean;
    "version"?: string;
    "installedVersion"?: string;
    "latestVersion"?: string;
    "hash"?: string;
    "installedHash"?: string;
    "path"?: string;
    "detail"?: string;

    /** Creates a new Item instance. */
    constructor($$source: Partial<Item> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("selectedByDefault" in $$source)) {
            this["selectedByDefault"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Item instance from a string or object.
     */
    static createFrom($$source: any = {}): Item {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Item($$parsedSource as Partial<Item>);
    }
}
