// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

export class Bookmark {
    "id": string;
    "ptyId": string;
    "sessionId": string;
    "windowId": string;
    "paneId": string;
    "offset": number;
    "kind": string;
    "label": string;
    "createdAt": time$0.Time;

    /** Creates a new Bookmark instance. */
    constructor($$source: Partial<Bookmark> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("ptyId" in $$source)) {
            this["ptyId"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("windowId" in $$source)) {
            this["windowId"] = "";
        }
        if (!("paneId" in $$source)) {
            this["paneId"] = "";
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Bookmark instance from a string or object.
     */
    static createFrom($$source: any = {}): Bookmark {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Bookmark($$parsedSource as Partial<Bookmark>);
    }
}
