// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as session$0 from "../domain/session/models.js";

export class CreatedSession {
    "Session": session$0.Session;
    "MainPtyID": string;

    /** Creates a new CreatedSession instance. */
    constructor($$source: Partial<CreatedSession> = {}) {
        if (!("Session" in $$source)) {
            this["Session"] = (new session$0.Session());
        }
        if (!("MainPtyID" in $$source)) {
            this["MainPtyID"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreatedSession instance from a string or object.
     */
    static createFrom($$source: any = {}): CreatedSession {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Session" in $$parsedSource) {
            $$parsedSource["Session"] = $$createField0_0($$parsedSource["Session"]);
        }
        return new CreatedSession($$parsedSource as Partial<CreatedSession>);
    }
}

export class SplitPaneResult {
    "Session": session$0.Session;
    "PaneID": string;
    "PtyID": string;

    /** Creates a new SplitPaneResult instance. */
    constructor($$source: Partial<SplitPaneResult> = {}) {
        if (!("Session" in $$source)) {
            this["Session"] = (new session$0.Session());
        }
        if (!("PaneID" in $$source)) {
            this["PaneID"] = "";
        }
        if (!("PtyID" in $$source)) {
            this["PtyID"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SplitPaneResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SplitPaneResult {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Session" in $$parsedSource) {
            $$parsedSource["Session"] = $$createField0_0($$parsedSource["Session"]);
        }
        return new SplitPaneResult($$parsedSource as Partial<SplitPaneResult>);
    }
}

// Private type creation functions
const $$createType0 = session$0.Session.createFrom;
