// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DaemonStatus describes the daemon the app talks to, for the daemon preferences panel.
 */
export class DaemonStatus {
    /**
     * Running is true when the daemon answers health checks.
     */
    "running": boolean;

    /**
     * Address is the daemon URL (e.g. http://127.0.0.1:8787).
     */
    "address": string;

    /**
     * ControlToken is used by the renderer only for daemon WebSocket attach handshakes.
     */
    "controlToken": string;

    /**
     * Managed is true when this app started the daemon (the state file matches its live process),
     * as opposed to one started independently (e.g. `whisk daemon run`).
     */
    "managed": boolean;

    /**
     * Protocol/build fields come from the daemon's compatibility endpoint when it is reachable.
     */
    "apiVersion": number;
    "protocolVersion": number;
    "supportedPreviousProtocolVersions"?: number[];
    "gitSha": string;
    "version": string;
    "dirty": boolean;

    /**
     * Error holds a human-readable reason when the daemon is unreachable or incompatible.
     */
    "error": string;

    /**
     * AutoRestartEnabled mirrors the opt-in app preference used by the client-side watcher.
     */
    "autoRestartEnabled": boolean;

    /**
     * Restarting is true while the watcher is actively trying to re-ensure a managed daemon.
     */
    "restarting": boolean;

    /**
     * RestartAttempt is the current bounded auto-restart attempt number, when any.
     */
    "restartAttempt": number;

    /**
     * RestartMaxAttempts is the retry budget for one unexpected managed-daemon loss.
     */
    "restartMaxAttempts": number;

    /**
     * AutoRestartExhausted is true after the watcher spends the bounded retry budget.
     */
    "autoRestartExhausted": boolean;

    /** Creates a new DaemonStatus instance. */
    constructor($$source: Partial<DaemonStatus> = {}) {
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("controlToken" in $$source)) {
            this["controlToken"] = "";
        }
        if (!("managed" in $$source)) {
            this["managed"] = false;
        }
        if (!("apiVersion" in $$source)) {
            this["apiVersion"] = 0;
        }
        if (!("protocolVersion" in $$source)) {
            this["protocolVersion"] = 0;
        }
        if (!("gitSha" in $$source)) {
            this["gitSha"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("dirty" in $$source)) {
            this["dirty"] = false;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("autoRestartEnabled" in $$source)) {
            this["autoRestartEnabled"] = false;
        }
        if (!("restarting" in $$source)) {
            this["restarting"] = false;
        }
        if (!("restartAttempt" in $$source)) {
            this["restartAttempt"] = 0;
        }
        if (!("restartMaxAttempts" in $$source)) {
            this["restartMaxAttempts"] = 0;
        }
        if (!("autoRestartExhausted" in $$source)) {
            this["autoRestartExhausted"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DaemonStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): DaemonStatus {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("supportedPreviousProtocolVersions" in $$parsedSource) {
            $$parsedSource["supportedPreviousProtocolVersions"] = $$createField6_0($$parsedSource["supportedPreviousProtocolVersions"]);
        }
        return new DaemonStatus($$parsedSource as Partial<DaemonStatus>);
    }
}

export class NotificationFocusContext {
    "activeMain"?: string;
    "sessionId"?: string;
    "paneId"?: string;
    "windowFocused": boolean;

    /** Creates a new NotificationFocusContext instance. */
    constructor($$source: Partial<NotificationFocusContext> = {}) {
        if (!("windowFocused" in $$source)) {
            this["windowFocused"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NotificationFocusContext instance from a string or object.
     */
    static createFrom($$source: any = {}): NotificationFocusContext {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NotificationFocusContext($$parsedSource as Partial<NotificationFocusContext>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
