// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DaemonStatus describes the daemon the app talks to, for the daemon preferences panel.
 */
export class DaemonStatus {
    /**
     * Running is true when the daemon answers health checks.
     */
    "running": boolean;

    /**
     * Address is the daemon URL (e.g. http://127.0.0.1:8787).
     */
    "address": string;

    /**
     * Managed is true when this app started the daemon (a live PID file names it), as opposed to
     * one started independently (e.g. `whisk daemon run`).
     */
    "managed": boolean;

    /**
     * APIVersion and GitSHA come from the daemon's compatibility endpoint when it is reachable.
     */
    "apiVersion": number;
    "gitSha": string;
    "version": string;
    "dirty": boolean;

    /**
     * Error holds a human-readable reason when the daemon is unreachable or incompatible.
     */
    "error": string;

    /** Creates a new DaemonStatus instance. */
    constructor($$source: Partial<DaemonStatus> = {}) {
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("managed" in $$source)) {
            this["managed"] = false;
        }
        if (!("apiVersion" in $$source)) {
            this["apiVersion"] = 0;
        }
        if (!("gitSha" in $$source)) {
            this["gitSha"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("dirty" in $$source)) {
            this["dirty"] = false;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DaemonStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): DaemonStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DaemonStatus($$parsedSource as Partial<DaemonStatus>);
    }
}
