// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as appmenu$0 from "../appmenu/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as appsettings$0 from "../appsettings/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ptybookmark$0 from "../domain/ptybookmark/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as session$0 from "../domain/session/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workitem$0 from "../domain/workitem/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as protocol$0 from "../protocol/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddPTYBookmark(req: protocol$0.AddPTYBookmarkRequest): $CancellablePromise<protocol$0.PTYBookmark> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.AddPTYBookmark", req).then(($result: any) => {
        return $$createType0($result);
    });
}

export function AddProjectAttachment(req: protocol$0.AddProjectAttachmentRequest): $CancellablePromise<protocol$0.Project> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.AddProjectAttachment", req).then(($result: any) => {
        return $$createType1($result);
    });
}

export function AddWorkItemAttachment(req: protocol$0.AddWorkItemAttachmentRequest): $CancellablePromise<protocol$0.WorkItem> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.AddWorkItemAttachment", req).then(($result: any) => {
        return $$createType2($result);
    });
}

export function AgentHookLogStatus(): $CancellablePromise<protocol$0.AgentHookLogStatus> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.AgentHookLogStatus").then(($result: any) => {
        return $$createType3($result);
    });
}

export function AnswerQuestion(req: protocol$0.AnswerQuestionRequest): $CancellablePromise<protocol$0.Question> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.AnswerQuestion", req).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ApplyOnboarding(req: protocol$0.OnboardingApplyRequest): $CancellablePromise<protocol$0.OnboardingStatus> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.ApplyOnboarding", req).then(($result: any) => {
        return $$createType5($result);
    });
}

export function ApproveDone(req: protocol$0.ApproveDoneRequest): $CancellablePromise<protocol$0.WorkItem> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.ApproveDone", req).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ApprovePlan(req: protocol$0.ApprovePlanRequest): $CancellablePromise<protocol$0.WorkItem> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.ApprovePlan", req).then(($result: any) => {
        return $$createType2($result);
    });
}

export function AskQuestion(req: protocol$0.AskQuestionRequest): $CancellablePromise<protocol$0.Question> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.AskQuestion", req).then(($result: any) => {
        return $$createType4($result);
    });
}

export function BindWorkItemWorktree(req: protocol$0.BindWorkItemWorktreeRequest): $CancellablePromise<protocol$0.WorkItem> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.BindWorkItemWorktree", req).then(($result: any) => {
        return $$createType2($result);
    });
}

export function CancelWorkItemRun(req: protocol$0.CancelWorkItemRunRequest): $CancellablePromise<protocol$0.WorkItemRun> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.CancelWorkItemRun", req).then(($result: any) => {
        return $$createType6($result);
    });
}

export function CheckAgentHookIntegration(req: protocol$0.AgentHookIntegrationRequest): $CancellablePromise<protocol$0.AgentHookIntegration> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.CheckAgentHookIntegration", req).then(($result: any) => {
        return $$createType7($result);
    });
}

export function ClearAgentHookLog(): $CancellablePromise<protocol$0.AgentHookLogStatus> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.ClearAgentHookLog").then(($result: any) => {
        return $$createType3($result);
    });
}

export function ClearDaemon(req: protocol$0.ClearDaemonRequest): $CancellablePromise<protocol$0.ClearDaemonResponse> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.ClearDaemon", req).then(($result: any) => {
        return $$createType8($result);
    });
}

export function ClosePane(req: protocol$0.ClosePaneRequest): $CancellablePromise<session$0.Session> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.ClosePane", req).then(($result: any) => {
        return $$createType9($result);
    });
}

export function CloseSession(req: protocol$0.CloseSessionRequest): $CancellablePromise<session$0.Session[]> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.CloseSession", req).then(($result: any) => {
        return $$createType10($result);
    });
}

export function CompleteExecution(req: protocol$0.CompleteExecutionRequest): $CancellablePromise<protocol$0.WorkItem> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.CompleteExecution", req).then(($result: any) => {
        return $$createType2($result);
    });
}

export function CompleteGate(req: protocol$0.CompleteGateRequest): $CancellablePromise<protocol$0.GateReport> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.CompleteGate", req).then(($result: any) => {
        return $$createType11($result);
    });
}

export function CreateProject(req: protocol$0.CreateProjectRequest): $CancellablePromise<protocol$0.Project> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.CreateProject", req).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateSession(req: protocol$0.CreateSessionRequest): $CancellablePromise<protocol$0.CreatedSession> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.CreateSession", req).then(($result: any) => {
        return $$createType12($result);
    });
}

export function CreateWorkItem(req: protocol$0.CreateWorkItemRequest): $CancellablePromise<protocol$0.WorkItem> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.CreateWorkItem", req).then(($result: any) => {
        return $$createType2($result);
    });
}

export function CreateWorktree(req: protocol$0.CreateWorktreeRequest): $CancellablePromise<protocol$0.CreatedWorktree> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.CreateWorktree", req).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * DaemonStatus reports the current state of the daemon for display in the preferences panel.
 */
export function DaemonStatus(): $CancellablePromise<$models.DaemonStatus> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.DaemonStatus").then(($result: any) => {
        return $$createType14($result);
    });
}

export function DeletePTY(req: protocol$0.DeletePTYRequest): $CancellablePromise<void> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.DeletePTY", req);
}

export function DeleteProjectAttachment(attachmentID: string, req: protocol$0.DeleteProjectAttachmentRequest): $CancellablePromise<protocol$0.Project> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.DeleteProjectAttachment", attachmentID, req).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteWorkItem(req: protocol$0.DeleteWorkItemRequest): $CancellablePromise<protocol$0.WorkItem> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.DeleteWorkItem", req).then(($result: any) => {
        return $$createType2($result);
    });
}

export function DetachPanePTY(req: protocol$0.DetachPanePTYRequest): $CancellablePromise<protocol$0.DetachedPanePTY> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.DetachPanePTY", req).then(($result: any) => {
        return $$createType15($result);
    });
}

export function DetectWorktrunk(req: protocol$0.DetectWorktrunkRequest): $CancellablePromise<protocol$0.WorktrunkStatus> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.DetectWorktrunk", req).then(($result: any) => {
        return $$createType16($result);
    });
}

export function InstallAgentHookIntegration(req: protocol$0.AgentHookIntegrationRequest): $CancellablePromise<protocol$0.AgentHookIntegration> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.InstallAgentHookIntegration", req).then(($result: any) => {
        return $$createType7($result);
    });
}

export function InstallPlugin(registry: string, id: string): $CancellablePromise<protocol$0.PluginStatus> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.InstallPlugin", registry, id).then(($result: any) => {
        return $$createType17($result);
    });
}

export function KillPTY(req: protocol$0.KillPTYRequest): $CancellablePromise<protocol$0.PTYInfo> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.KillPTY", req).then(($result: any) => {
        return $$createType18($result);
    });
}

export function LaunchExecution(req: protocol$0.LaunchExecutionRequest): $CancellablePromise<protocol$0.WorkItemRun> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.LaunchExecution", req).then(($result: any) => {
        return $$createType6($result);
    });
}

export function LaunchWorkItemRun(req: protocol$0.LaunchWorkItemRunRequest): $CancellablePromise<protocol$0.WorkItemRun> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.LaunchWorkItemRun", req).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ListAgentBridgeApprovals(req: protocol$0.ListAgentBridgeApprovalsRequest): $CancellablePromise<protocol$0.AgentBridgeApproval[]> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.ListAgentBridgeApprovals", req).then(($result: any) => {
        return $$createType20($result);
    });
}

export function ListAgentBridgeEvents(req: protocol$0.ListAgentBridgeEventsRequest): $CancellablePromise<protocol$0.AgentBridgeEvent[]> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.ListAgentBridgeEvents", req).then(($result: any) => {
        return $$createType22($result);
    });
}

export function ListAgentHookIntegrations(): $CancellablePromise<protocol$0.AgentHookIntegration[]> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.ListAgentHookIntegrations").then(($result: any) => {
        return $$createType23($result);
    });
}

export function ListArtifacts(workItemID: string): $CancellablePromise<protocol$0.Artifact[]> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.ListArtifacts", workItemID).then(($result: any) => {
        return $$createType25($result);
    });
}

export function ListGateReports(workItemID: string): $CancellablePromise<protocol$0.GateReport[]> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.ListGateReports", workItemID).then(($result: any) => {
        return $$createType26($result);
    });
}

export function ListHTTPForwards(): $CancellablePromise<protocol$0.HTTPForward[]> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.ListHTTPForwards").then(($result: any) => {
        return $$createType28($result);
    });
}

export function ListPTYBookmarks(ptyID: string): $CancellablePromise<protocol$0.PTYBookmark[]> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.ListPTYBookmarks", ptyID).then(($result: any) => {
        return $$createType29($result);
    });
}

export function ListPTYHistory(): $CancellablePromise<protocol$0.PTYHistorySummary[]> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.ListPTYHistory").then(($result: any) => {
        return $$createType31($result);
    });
}

export function ListPTYs(): $CancellablePromise<protocol$0.PTYInfo[]> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.ListPTYs").then(($result: any) => {
        return $$createType32($result);
    });
}

export function ListPlugins(): $CancellablePromise<protocol$0.PluginStatus[]> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.ListPlugins").then(($result: any) => {
        return $$createType33($result);
    });
}

export function ListProjects(): $CancellablePromise<protocol$0.Project[]> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.ListProjects").then(($result: any) => {
        return $$createType34($result);
    });
}

export function ListPromptTemplates(): $CancellablePromise<protocol$0.PromptTemplate[]> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.ListPromptTemplates").then(($result: any) => {
        return $$createType36($result);
    });
}

export function ListQuestions(workItemID: string): $CancellablePromise<protocol$0.Question[]> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.ListQuestions", workItemID).then(($result: any) => {
        return $$createType37($result);
    });
}

export function ListRegistryPlugins(): $CancellablePromise<protocol$0.RegistryPlugin[]> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.ListRegistryPlugins").then(($result: any) => {
        return $$createType39($result);
    });
}

export function ListSessions(): $CancellablePromise<session$0.Session[]> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.ListSessions").then(($result: any) => {
        return $$createType10($result);
    });
}

export function ListStatusEvents(req: protocol$0.ListStatusEventsRequest): $CancellablePromise<protocol$0.StatusEvent[]> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.ListStatusEvents", req).then(($result: any) => {
        return $$createType41($result);
    });
}

export function ListWorkItemRuns(workItemID: string): $CancellablePromise<protocol$0.WorkItemRun[]> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.ListWorkItemRuns", workItemID).then(($result: any) => {
        return $$createType42($result);
    });
}

export function ListWorkItems(projectID: string): $CancellablePromise<protocol$0.WorkItem[]> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.ListWorkItems", projectID).then(($result: any) => {
        return $$createType43($result);
    });
}

export function ListWorkflowEvents(workItemID: string): $CancellablePromise<protocol$0.WorkflowEvent[]> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.ListWorkflowEvents", workItemID).then(($result: any) => {
        return $$createType45($result);
    });
}

export function ListWorkflowTemplates(): $CancellablePromise<protocol$0.WorkflowTemplate[]> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.ListWorkflowTemplates").then(($result: any) => {
        return $$createType47($result);
    });
}

export function ListWorktrees(req: protocol$0.ListWorktreesRequest): $CancellablePromise<protocol$0.Worktree[]> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.ListWorktrees", req).then(($result: any) => {
        return $$createType49($result);
    });
}

export function LoadAppSettings(): $CancellablePromise<appsettings$0.Settings> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.LoadAppSettings").then(($result: any) => {
        return $$createType50($result);
    });
}

/**
 * LoadKeybindings returns the command registry with each command's effective accelerator for the
 * Keyboard Shortcuts panel.
 */
export function LoadKeybindings(): $CancellablePromise<appmenu$0.KeybindingsView> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.LoadKeybindings").then(($result: any) => {
        return $$createType51($result);
    });
}

export function LogPTYTrace(line: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.LogPTYTrace", line);
}

export function MarkAgentBridgeEventRead(req: protocol$0.MarkAgentBridgeEventReadRequest): $CancellablePromise<protocol$0.AgentBridgeEvent> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.MarkAgentBridgeEventRead", req).then(($result: any) => {
        return $$createType21($result);
    });
}

export function MarkStatusEventRead(req: protocol$0.MarkStatusEventReadRequest): $CancellablePromise<protocol$0.StatusEvent> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.MarkStatusEventRead", req).then(($result: any) => {
        return $$createType40($result);
    });
}

export function MoveWorkItem(req: protocol$0.MoveWorkItemRequest): $CancellablePromise<protocol$0.WorkItem> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.MoveWorkItem", req).then(($result: any) => {
        return $$createType2($result);
    });
}

export function NextEvent(req: protocol$0.NextEventRequest): $CancellablePromise<protocol$0.RuntimeEvent> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.NextEvent", req).then(($result: any) => {
        return $$createType52($result);
    });
}

export function OnboardingStatus(): $CancellablePromise<protocol$0.OnboardingStatus> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.OnboardingStatus").then(($result: any) => {
        return $$createType5($result);
    });
}

export function OpenAgentHookLog(): $CancellablePromise<protocol$0.AgentHookLogStatus> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.OpenAgentHookLog").then(($result: any) => {
        return $$createType3($result);
    });
}

export function Output(req: protocol$0.OutputRequest): $CancellablePromise<protocol$0.OutputSnapshot> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.Output", req).then(($result: any) => {
        return $$createType53($result);
    });
}

export function PTYTraceEnabled(): $CancellablePromise<boolean> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.PTYTraceEnabled");
}

export function ProjectContext(projectID: string): $CancellablePromise<protocol$0.ProjectContext> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.ProjectContext", projectID).then(($result: any) => {
        return $$createType54($result);
    });
}

export function ProjectDetail(projectID: string): $CancellablePromise<protocol$0.ProjectDetail> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.ProjectDetail", projectID).then(($result: any) => {
        return $$createType55($result);
    });
}

export function QueueExecution(req: protocol$0.QueueExecutionRequest): $CancellablePromise<protocol$0.WorkItemRun> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.QueueExecution", req).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ReadPTYHistory(ptyID: string): $CancellablePromise<protocol$0.PTYHistory> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.ReadPTYHistory", ptyID).then(($result: any) => {
        return $$createType56($result);
    });
}

export function RemoveAgentHookIntegration(req: protocol$0.AgentHookIntegrationRequest): $CancellablePromise<protocol$0.AgentHookIntegration> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.RemoveAgentHookIntegration", req).then(($result: any) => {
        return $$createType7($result);
    });
}

export function RemovePTYBookmark(req: protocol$0.RemovePTYBookmarkRequest): $CancellablePromise<void> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.RemovePTYBookmark", req);
}

export function RemoveWorktree(req: protocol$0.RemoveWorktreeRequest): $CancellablePromise<void> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.RemoveWorktree", req);
}

export function ReportStatus(req: protocol$0.ReportStatusRequest): $CancellablePromise<protocol$0.ReportStatusResponse> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.ReportStatus", req).then(($result: any) => {
        return $$createType57($result);
    });
}

export function RescanPlugins(): $CancellablePromise<protocol$0.PluginStatus[]> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.RescanPlugins").then(($result: any) => {
        return $$createType33($result);
    });
}

export function ResizePTY(req: protocol$0.ResizePTYRequest): $CancellablePromise<void> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.ResizePTY", req);
}

export function ResolveAgentBridgeApproval(id: string, req: protocol$0.ResolveAgentBridgeApprovalRequest): $CancellablePromise<protocol$0.AgentBridgeApproval> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.ResolveAgentBridgeApproval", id, req).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * RestartDaemon stops the daemon and starts a fresh one, returning the resulting status.
 */
export function RestartDaemon(): $CancellablePromise<$models.DaemonStatus> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.RestartDaemon").then(($result: any) => {
        return $$createType14($result);
    });
}

export function RestartPanePTY(req: protocol$0.RestartPanePTYRequest): $CancellablePromise<protocol$0.RestartedPanePTY> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.RestartPanePTY", req).then(($result: any) => {
        return $$createType58($result);
    });
}

export function RunPluginProjectAttachmentTemplate(pluginID: string, templateID: string, req: protocol$0.RunPluginProjectAttachmentTemplateRequest): $CancellablePromise<protocol$0.Project> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.RunPluginProjectAttachmentTemplate", pluginID, templateID, req).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SaveAppSettings(settings: appsettings$0.Settings): $CancellablePromise<appsettings$0.Settings> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.SaveAppSettings", settings).then(($result: any) => {
        return $$createType50($result);
    });
}

/**
 * SaveKeybindings validates the proposed overrides, persists them, re-applies them to the live
 * menu, and returns the resulting effective bindings. The panel sends the full set of editable
 * bindings; only entries that differ from their default are persisted.
 */
export function SaveKeybindings(overrides: { [_ in string]?: string }): $CancellablePromise<appmenu$0.KeybindingsView> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.SaveKeybindings", overrides).then(($result: any) => {
        return $$createType51($result);
    });
}

export function SetAgentHookLogSettings(req: protocol$0.SetAgentHookLogSettingsRequest): $CancellablePromise<protocol$0.AgentHookLogStatus> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.SetAgentHookLogSettings", req).then(($result: any) => {
        return $$createType3($result);
    });
}

export function SetPaneWorkingDir(req: protocol$0.SetPaneWorkingDirRequest): $CancellablePromise<session$0.Session> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.SetPaneWorkingDir", req).then(($result: any) => {
        return $$createType9($result);
    });
}

export function SetSessionProject(req: protocol$0.SetSessionProjectRequest): $CancellablePromise<session$0.Session> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.SetSessionProject", req).then(($result: any) => {
        return $$createType9($result);
    });
}

export function SetSessionRootDir(req: protocol$0.SetSessionRootDirRequest): $CancellablePromise<session$0.Session> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.SetSessionRootDir", req).then(($result: any) => {
        return $$createType9($result);
    });
}

export function SplitPane(req: protocol$0.SplitPaneRequest): $CancellablePromise<protocol$0.SplitPaneResult> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.SplitPane", req).then(($result: any) => {
        return $$createType59($result);
    });
}

/**
 * StartDaemon starts a daemon if one is not already running, then returns the resulting status.
 */
export function StartDaemon(): $CancellablePromise<$models.DaemonStatus> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.StartDaemon").then(($result: any) => {
        return $$createType14($result);
    });
}

export function StartExecution(req: protocol$0.StartExecutionRequest): $CancellablePromise<protocol$0.WorkItemRun> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.StartExecution", req).then(($result: any) => {
        return $$createType6($result);
    });
}

export function StartHTTPForward(req: protocol$0.StartHTTPForwardRequest): $CancellablePromise<protocol$0.StartedHTTPForward> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.StartHTTPForward", req).then(($result: any) => {
        return $$createType60($result);
    });
}

export function StartPanePTY(req: protocol$0.StartPanePTYRequest): $CancellablePromise<protocol$0.StartedPanePTY> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.StartPanePTY", req).then(($result: any) => {
        return $$createType61($result);
    });
}

export function StartPlanning(req: protocol$0.StartPlanningRequest): $CancellablePromise<protocol$0.WorkItemRun> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.StartPlanning", req).then(($result: any) => {
        return $$createType6($result);
    });
}

export function StartWorkItemRun(req: protocol$0.StartWorkItemRunRequest): $CancellablePromise<protocol$0.WorkItemRun> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.StartWorkItemRun", req).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * StopDaemon shuts the daemon down and returns the resulting status.
 */
export function StopDaemon(): $CancellablePromise<$models.DaemonStatus> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.StopDaemon").then(($result: any) => {
        return $$createType14($result);
    });
}

export function StopHTTPForward(id: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.StopHTTPForward", id);
}

export function SubmitDraftPlan(req: protocol$0.SubmitDraftPlanRequest): $CancellablePromise<protocol$0.Artifact> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.SubmitDraftPlan", req).then(($result: any) => {
        return $$createType24($result);
    });
}

export function SubmitReviewFeedback(req: protocol$0.SubmitReviewFeedbackRequest): $CancellablePromise<protocol$0.Artifact> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.SubmitReviewFeedback", req).then(($result: any) => {
        return $$createType24($result);
    });
}

/**
 * SyncSessionMenu replaces the Sessions menu contents with the supplied list (in session-bar
 * order), keeping the native menu's names and Cmd+1..Cmd+0 shortcuts in step with the UI.
 */
export function SyncSessionMenu(sessions: appmenu$0.SessionRef[]): $CancellablePromise<void> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.SyncSessionMenu", sessions);
}

export function TrustPlugin(id: string): $CancellablePromise<protocol$0.PluginStatus> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.TrustPlugin", id).then(($result: any) => {
        return $$createType17($result);
    });
}

export function UntrustPlugin(id: string): $CancellablePromise<protocol$0.PluginStatus> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.UntrustPlugin", id).then(($result: any) => {
        return $$createType17($result);
    });
}

export function UpdateProject(projectID: string, req: protocol$0.UpdateProjectRequest): $CancellablePromise<protocol$0.Project> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.UpdateProject", projectID, req).then(($result: any) => {
        return $$createType1($result);
    });
}

export function UpdateProjectAttachment(attachmentID: string, req: protocol$0.UpdateProjectAttachmentRequest): $CancellablePromise<protocol$0.Project> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.UpdateProjectAttachment", attachmentID, req).then(($result: any) => {
        return $$createType1($result);
    });
}

export function WritePTY(req: protocol$0.WritePTYRequest): $CancellablePromise<void> {
    return $Call.ByName("github.com/phin-tech/whisk/internal/wailsapp.Service.WritePTY", req);
}

// Private type creation functions
const $$createType0 = ptybookmark$0.Bookmark.createFrom;
const $$createType1 = workitem$0.Project.createFrom;
const $$createType2 = workitem$0.WorkItem.createFrom;
const $$createType3 = protocol$0.AgentHookLogStatus.createFrom;
const $$createType4 = workitem$0.Question.createFrom;
const $$createType5 = protocol$0.OnboardingStatus.createFrom;
const $$createType6 = workitem$0.WorkItemRun.createFrom;
const $$createType7 = protocol$0.AgentHookIntegration.createFrom;
const $$createType8 = protocol$0.ClearDaemonResponse.createFrom;
const $$createType9 = session$0.Session.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = workitem$0.GateReport.createFrom;
const $$createType12 = protocol$0.CreatedSession.createFrom;
const $$createType13 = protocol$0.CreatedWorktree.createFrom;
const $$createType14 = $models.DaemonStatus.createFrom;
const $$createType15 = protocol$0.DetachedPanePTY.createFrom;
const $$createType16 = protocol$0.WorktrunkStatus.createFrom;
const $$createType17 = protocol$0.PluginStatus.createFrom;
const $$createType18 = protocol$0.PTYInfo.createFrom;
const $$createType19 = protocol$0.AgentBridgeApproval.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = protocol$0.AgentBridgeEvent.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = $Create.Array($$createType7);
const $$createType24 = workitem$0.Artifact.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = $Create.Array($$createType11);
const $$createType27 = protocol$0.HTTPForward.createFrom;
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = $Create.Array($$createType0);
const $$createType30 = protocol$0.PTYHistorySummary.createFrom;
const $$createType31 = $Create.Array($$createType30);
const $$createType32 = $Create.Array($$createType18);
const $$createType33 = $Create.Array($$createType17);
const $$createType34 = $Create.Array($$createType1);
const $$createType35 = workitem$0.PromptTemplate.createFrom;
const $$createType36 = $Create.Array($$createType35);
const $$createType37 = $Create.Array($$createType4);
const $$createType38 = protocol$0.RegistryPlugin.createFrom;
const $$createType39 = $Create.Array($$createType38);
const $$createType40 = workitem$0.StatusEvent.createFrom;
const $$createType41 = $Create.Array($$createType40);
const $$createType42 = $Create.Array($$createType6);
const $$createType43 = $Create.Array($$createType2);
const $$createType44 = workitem$0.WorkflowEvent.createFrom;
const $$createType45 = $Create.Array($$createType44);
const $$createType46 = workitem$0.WorkflowTemplate.createFrom;
const $$createType47 = $Create.Array($$createType46);
const $$createType48 = protocol$0.Worktree.createFrom;
const $$createType49 = $Create.Array($$createType48);
const $$createType50 = appsettings$0.Settings.createFrom;
const $$createType51 = appmenu$0.KeybindingsView.createFrom;
const $$createType52 = protocol$0.RuntimeEvent.createFrom;
const $$createType53 = protocol$0.OutputSnapshot.createFrom;
const $$createType54 = protocol$0.ProjectContext.createFrom;
const $$createType55 = protocol$0.ProjectDetail.createFrom;
const $$createType56 = protocol$0.PTYHistory.createFrom;
const $$createType57 = protocol$0.ReportStatusResponse.createFrom;
const $$createType58 = protocol$0.RestartedPanePTY.createFrom;
const $$createType59 = protocol$0.SplitPaneResult.createFrom;
const $$createType60 = protocol$0.StartedHTTPForward.createFrom;
const $$createType61 = protocol$0.StartedPanePTY.createFrom;
