// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

export class Artifact {
    "id": string;
    "projectId": string;
    "workItemId": string;
    "runId"?: string;
    "kind": string;
    "status": string;
    "title"?: string;
    "body"?: string;
    "metadata"?: { [_ in string]?: MetadataValue };
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new Artifact instance. */
    constructor($$source: Partial<Artifact> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("workItemId" in $$source)) {
            this["workItemId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Artifact instance from a string or object.
     */
    static createFrom($$source: any = {}): Artifact {
        const $$createField8_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField8_0($$parsedSource["metadata"]);
        }
        return new Artifact($$parsedSource as Partial<Artifact>);
    }
}

export class Attachment {
    "id": string;
    "kind": string;
    "scope": string;
    "title"?: string;
    "path"?: string;
    "url"?: string;
    "note"?: string;
    "provider"?: string;
    "target"?: string;
    "includeInContext"?: boolean;
    "meta"?: { [_ in string]?: MetadataValue };
    "createdAt": time$0.Time;

    /** Creates a new Attachment instance. */
    constructor($$source: Partial<Attachment> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("scope" in $$source)) {
            this["scope"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Attachment instance from a string or object.
     */
    static createFrom($$source: any = {}): Attachment {
        const $$createField10_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("meta" in $$parsedSource) {
            $$parsedSource["meta"] = $$createField10_0($$parsedSource["meta"]);
        }
        return new Attachment($$parsedSource as Partial<Attachment>);
    }
}

export class BlockedWorkItem {
    "workItem": WorkItem;
    "blockedBy": ReadyBlockerInfo[];
    "blockedByCount": number;

    /** Creates a new BlockedWorkItem instance. */
    constructor($$source: Partial<BlockedWorkItem> = {}) {
        if (!("workItem" in $$source)) {
            this["workItem"] = (new WorkItem());
        }
        if (!("blockedBy" in $$source)) {
            this["blockedBy"] = [];
        }
        if (!("blockedByCount" in $$source)) {
            this["blockedByCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BlockedWorkItem instance from a string or object.
     */
    static createFrom($$source: any = {}): BlockedWorkItem {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("workItem" in $$parsedSource) {
            $$parsedSource["workItem"] = $$createField0_0($$parsedSource["workItem"]);
        }
        if ("blockedBy" in $$parsedSource) {
            $$parsedSource["blockedBy"] = $$createField1_0($$parsedSource["blockedBy"]);
        }
        return new BlockedWorkItem($$parsedSource as Partial<BlockedWorkItem>);
    }
}

export class GateConfig {
    "id": string;
    "name": string;
    "kind": string;
    "command"?: string;
    "skill"?: string;
    "blocking": boolean;
    "phase"?: string;

    /** Creates a new GateConfig instance. */
    constructor($$source: Partial<GateConfig> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("blocking" in $$source)) {
            this["blocking"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GateConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): GateConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GateConfig($$parsedSource as Partial<GateConfig>);
    }
}

export class GateReport {
    "id": string;
    "projectId": string;
    "workItemId": string;
    "runId"?: string;
    "name": string;
    "blocking": boolean;
    "status": string;
    "overrideReason"?: string;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new GateReport instance. */
    constructor($$source: Partial<GateReport> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("workItemId" in $$source)) {
            this["workItemId"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("blocking" in $$source)) {
            this["blocking"] = false;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GateReport instance from a string or object.
     */
    static createFrom($$source: any = {}): GateReport {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GateReport($$parsedSource as Partial<GateReport>);
    }
}

export class HistoryEvent {
    "id": string;
    "type": string;
    "at": time$0.Time;
    "actor"?: string;
    "message"?: string;
    "stageId"?: string;
    "attachmentId"?: string;
    "branch"?: string;
    "worktreePath"?: string;

    /** Creates a new HistoryEvent instance. */
    constructor($$source: Partial<HistoryEvent> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("at" in $$source)) {
            this["at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryEvent($$parsedSource as Partial<HistoryEvent>);
    }
}

export class MetadataValue {
    "type": string;
    "string"?: string;
    "number"?: number;
    "bool"?: boolean;
    "json"?: json$0.RawMessage;

    /** Creates a new MetadataValue instance. */
    constructor($$source: Partial<MetadataValue> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MetadataValue instance from a string or object.
     */
    static createFrom($$source: any = {}): MetadataValue {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MetadataValue($$parsedSource as Partial<MetadataValue>);
    }
}

export class Project {
    "id": string;
    "name": string;
    "description"?: string;
    "slug": string;
    "rootDir": string;
    "workflow": ProjectWorkflow;
    "preferences": ProjectPreferences;
    "attachments": Attachment[];
    "metadata"?: { [_ in string]?: MetadataValue };
    "nextWorkItemNumber": number;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new Project instance. */
    constructor($$source: Partial<Project> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("slug" in $$source)) {
            this["slug"] = "";
        }
        if (!("rootDir" in $$source)) {
            this["rootDir"] = "";
        }
        if (!("workflow" in $$source)) {
            this["workflow"] = (new ProjectWorkflow());
        }
        if (!("preferences" in $$source)) {
            this["preferences"] = (new ProjectPreferences());
        }
        if (!("attachments" in $$source)) {
            this["attachments"] = [];
        }
        if (!("nextWorkItemNumber" in $$source)) {
            this["nextWorkItemNumber"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Project instance from a string or object.
     */
    static createFrom($$source: any = {}): Project {
        const $$createField5_0 = $$createType5;
        const $$createField6_0 = $$createType6;
        const $$createField7_0 = $$createType8;
        const $$createField8_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("workflow" in $$parsedSource) {
            $$parsedSource["workflow"] = $$createField5_0($$parsedSource["workflow"]);
        }
        if ("preferences" in $$parsedSource) {
            $$parsedSource["preferences"] = $$createField6_0($$parsedSource["preferences"]);
        }
        if ("attachments" in $$parsedSource) {
            $$parsedSource["attachments"] = $$createField7_0($$parsedSource["attachments"]);
        }
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField8_0($$parsedSource["metadata"]);
        }
        return new Project($$parsedSource as Partial<Project>);
    }
}

export class ProjectPreferences {
    "autoRun": string;
    "autoWorktree": boolean;
    "useInteractiveAgentShell"?: boolean;
    "defaultPhaseAgents"?: { [_ in string]?: string };
    "gates"?: GateConfig[];

    /** Creates a new ProjectPreferences instance. */
    constructor($$source: Partial<ProjectPreferences> = {}) {
        if (!("autoRun" in $$source)) {
            this["autoRun"] = "";
        }
        if (!("autoWorktree" in $$source)) {
            this["autoWorktree"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectPreferences instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectPreferences {
        const $$createField3_0 = $$createType9;
        const $$createField4_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("defaultPhaseAgents" in $$parsedSource) {
            $$parsedSource["defaultPhaseAgents"] = $$createField3_0($$parsedSource["defaultPhaseAgents"]);
        }
        if ("gates" in $$parsedSource) {
            $$parsedSource["gates"] = $$createField4_0($$parsedSource["gates"]);
        }
        return new ProjectPreferences($$parsedSource as Partial<ProjectPreferences>);
    }
}

export class ProjectWorkflow {
    "id": string;
    "templateId": string;
    "definitionId"?: string;
    "definitionVersion"?: number;
    "definitionHash"?: string;
    "name": string;
    "stages": WorkflowStage[];
    "transitionRules": TransitionRule[];

    /** Creates a new ProjectWorkflow instance. */
    constructor($$source: Partial<ProjectWorkflow> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("templateId" in $$source)) {
            this["templateId"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("stages" in $$source)) {
            this["stages"] = [];
        }
        if (!("transitionRules" in $$source)) {
            this["transitionRules"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectWorkflow instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectWorkflow {
        const $$createField6_0 = $$createType13;
        const $$createField7_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stages" in $$parsedSource) {
            $$parsedSource["stages"] = $$createField6_0($$parsedSource["stages"]);
        }
        if ("transitionRules" in $$parsedSource) {
            $$parsedSource["transitionRules"] = $$createField7_0($$parsedSource["transitionRules"]);
        }
        return new ProjectWorkflow($$parsedSource as Partial<ProjectWorkflow>);
    }
}

export class PromptTemplate {
    "id": string;
    "name": string;
    "source": string;
    "body": string;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new PromptTemplate instance. */
    constructor($$source: Partial<PromptTemplate> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PromptTemplate instance from a string or object.
     */
    static createFrom($$source: any = {}): PromptTemplate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PromptTemplate($$parsedSource as Partial<PromptTemplate>);
    }
}

export class Question {
    "id": string;
    "projectId": string;
    "workItemId": string;
    "runId"?: string;
    "sessionId"?: string;
    "ptyId"?: string;
    "prompt": string;
    "answer"?: string;
    "status": string;
    "actor"?: string;
    "answeredBy"?: string;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;
    "answeredAt"?: time$0.Time | null;

    /** Creates a new Question instance. */
    constructor($$source: Partial<Question> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("workItemId" in $$source)) {
            this["workItemId"] = "";
        }
        if (!("prompt" in $$source)) {
            this["prompt"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Question instance from a string or object.
     */
    static createFrom($$source: any = {}): Question {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Question($$parsedSource as Partial<Question>);
    }
}

export class ReadyBlockerInfo {
    "id": string;
    "number"?: number;
    "title"?: string;
    "stageId"?: string;
    "runState"?: string;

    /** Creates a new ReadyBlockerInfo instance. */
    constructor($$source: Partial<ReadyBlockerInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReadyBlockerInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ReadyBlockerInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReadyBlockerInfo($$parsedSource as Partial<ReadyBlockerInfo>);
    }
}

export class ReadyWorkExplanation {
    "ready": ReadyWorkItem[];
    "blocked": BlockedWorkItem[];
    "cycles"?: string[][];
    "summary": ReadyWorkSummary;

    /** Creates a new ReadyWorkExplanation instance. */
    constructor($$source: Partial<ReadyWorkExplanation> = {}) {
        if (!("ready" in $$source)) {
            this["ready"] = [];
        }
        if (!("blocked" in $$source)) {
            this["blocked"] = [];
        }
        if (!("summary" in $$source)) {
            this["summary"] = (new ReadyWorkSummary());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReadyWorkExplanation instance from a string or object.
     */
    static createFrom($$source: any = {}): ReadyWorkExplanation {
        const $$createField0_0 = $$createType17;
        const $$createField1_0 = $$createType19;
        const $$createField2_0 = $$createType21;
        const $$createField3_0 = $$createType22;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ready" in $$parsedSource) {
            $$parsedSource["ready"] = $$createField0_0($$parsedSource["ready"]);
        }
        if ("blocked" in $$parsedSource) {
            $$parsedSource["blocked"] = $$createField1_0($$parsedSource["blocked"]);
        }
        if ("cycles" in $$parsedSource) {
            $$parsedSource["cycles"] = $$createField2_0($$parsedSource["cycles"]);
        }
        if ("summary" in $$parsedSource) {
            $$parsedSource["summary"] = $$createField3_0($$parsedSource["summary"]);
        }
        return new ReadyWorkExplanation($$parsedSource as Partial<ReadyWorkExplanation>);
    }
}

export class ReadyWorkItem {
    "workItem": WorkItem;
    "reason": string;
    "resolvedBlockers"?: string[];
    "dependencyCount": number;
    "dependentCount": number;
    "parentWorkItemId"?: string | null;

    /** Creates a new ReadyWorkItem instance. */
    constructor($$source: Partial<ReadyWorkItem> = {}) {
        if (!("workItem" in $$source)) {
            this["workItem"] = (new WorkItem());
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }
        if (!("dependencyCount" in $$source)) {
            this["dependencyCount"] = 0;
        }
        if (!("dependentCount" in $$source)) {
            this["dependentCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReadyWorkItem instance from a string or object.
     */
    static createFrom($$source: any = {}): ReadyWorkItem {
        const $$createField0_0 = $$createType2;
        const $$createField2_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("workItem" in $$parsedSource) {
            $$parsedSource["workItem"] = $$createField0_0($$parsedSource["workItem"]);
        }
        if ("resolvedBlockers" in $$parsedSource) {
            $$parsedSource["resolvedBlockers"] = $$createField2_0($$parsedSource["resolvedBlockers"]);
        }
        return new ReadyWorkItem($$parsedSource as Partial<ReadyWorkItem>);
    }
}

export class ReadyWorkSummary {
    "totalReady": number;
    "totalBlocked": number;
    "cycleCount": number;

    /** Creates a new ReadyWorkSummary instance. */
    constructor($$source: Partial<ReadyWorkSummary> = {}) {
        if (!("totalReady" in $$source)) {
            this["totalReady"] = 0;
        }
        if (!("totalBlocked" in $$source)) {
            this["totalBlocked"] = 0;
        }
        if (!("cycleCount" in $$source)) {
            this["cycleCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReadyWorkSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): ReadyWorkSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReadyWorkSummary($$parsedSource as Partial<ReadyWorkSummary>);
    }
}

export class RunEvent {
    "id": string;
    "type": string;
    "at": time$0.Time;
    "actor"?: string;
    "message"?: string;

    /** Creates a new RunEvent instance. */
    constructor($$source: Partial<RunEvent> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("at" in $$source)) {
            this["at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): RunEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RunEvent($$parsedSource as Partial<RunEvent>);
    }
}

export class StatusEvent {
    "id": string;
    "scope": string;
    "kind": string;
    "message": string;
    "actor"?: string;
    "projectId"?: string;
    "workItemId"?: string;
    "runId"?: string;
    "sessionId"?: string;
    "paneId"?: string;
    "ptyId"?: string;
    "requiresAttention": boolean;
    "notificationKey"?: string;
    "notificationSeverity"?: string;
    "createdAt": time$0.Time;
    "readAt"?: time$0.Time | null;

    /** Creates a new StatusEvent instance. */
    constructor($$source: Partial<StatusEvent> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("scope" in $$source)) {
            this["scope"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("requiresAttention" in $$source)) {
            this["requiresAttention"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatusEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): StatusEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StatusEvent($$parsedSource as Partial<StatusEvent>);
    }
}

export class TransitionRule {
    "fromStageId": string;
    "toStageId": string;
    "requiresApproval"?: boolean;
    "requiresChecks"?: boolean;
    "requiresNoRunningRuns"?: boolean;

    /** Creates a new TransitionRule instance. */
    constructor($$source: Partial<TransitionRule> = {}) {
        if (!("fromStageId" in $$source)) {
            this["fromStageId"] = "";
        }
        if (!("toStageId" in $$source)) {
            this["toStageId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TransitionRule instance from a string or object.
     */
    static createFrom($$source: any = {}): TransitionRule {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TransitionRule($$parsedSource as Partial<TransitionRule>);
    }
}

export class WorkItem {
    "id": string;
    "projectId": string;
    "workflowId": string;
    "workflowVersion": number;
    "number": number;
    "title": string;
    "bodyMarkdown": string;
    "stageId": string;
    "previousStageId"?: string;
    "runState": string;
    "worktree"?: WorktreeBinding | null;
    "attachments": Attachment[];
    "metadata"?: { [_ in string]?: MetadataValue };
    "history": HistoryEvent[];
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new WorkItem instance. */
    constructor($$source: Partial<WorkItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("workflowId" in $$source)) {
            this["workflowId"] = "";
        }
        if (!("workflowVersion" in $$source)) {
            this["workflowVersion"] = 0;
        }
        if (!("number" in $$source)) {
            this["number"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("bodyMarkdown" in $$source)) {
            this["bodyMarkdown"] = "";
        }
        if (!("stageId" in $$source)) {
            this["stageId"] = "";
        }
        if (!("runState" in $$source)) {
            this["runState"] = "";
        }
        if (!("attachments" in $$source)) {
            this["attachments"] = [];
        }
        if (!("history" in $$source)) {
            this["history"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkItem instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkItem {
        const $$createField10_0 = $$createType24;
        const $$createField11_0 = $$createType8;
        const $$createField12_0 = $$createType1;
        const $$createField13_0 = $$createType26;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("worktree" in $$parsedSource) {
            $$parsedSource["worktree"] = $$createField10_0($$parsedSource["worktree"]);
        }
        if ("attachments" in $$parsedSource) {
            $$parsedSource["attachments"] = $$createField11_0($$parsedSource["attachments"]);
        }
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField12_0($$parsedSource["metadata"]);
        }
        if ("history" in $$parsedSource) {
            $$parsedSource["history"] = $$createField13_0($$parsedSource["history"]);
        }
        return new WorkItem($$parsedSource as Partial<WorkItem>);
    }
}

export class WorkItemLink {
    "id": string;
    "projectId": string;
    "sourceWorkItemId": string;
    "targetWorkItemId": string;
    "type": string;
    "createdBy"?: string;
    "createdAt": time$0.Time;

    /** Creates a new WorkItemLink instance. */
    constructor($$source: Partial<WorkItemLink> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("sourceWorkItemId" in $$source)) {
            this["sourceWorkItemId"] = "";
        }
        if (!("targetWorkItemId" in $$source)) {
            this["targetWorkItemId"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkItemLink instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkItemLink {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkItemLink($$parsedSource as Partial<WorkItemLink>);
    }
}

export class WorkItemRun {
    "id": string;
    "workItemId": string;
    "projectId": string;
    "preset": string;
    "promptTemplateId": string;
    "promptSnapshot": string;
    "sessionId"?: string;
    "ptyId"?: string;
    "status": string;
    "metadata"?: { [_ in string]?: MetadataValue };
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;
    "completedAt"?: time$0.Time | null;
    "history": RunEvent[];

    /** Creates a new WorkItemRun instance. */
    constructor($$source: Partial<WorkItemRun> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("workItemId" in $$source)) {
            this["workItemId"] = "";
        }
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("preset" in $$source)) {
            this["preset"] = "";
        }
        if (!("promptTemplateId" in $$source)) {
            this["promptTemplateId"] = "";
        }
        if (!("promptSnapshot" in $$source)) {
            this["promptSnapshot"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }
        if (!("history" in $$source)) {
            this["history"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkItemRun instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkItemRun {
        const $$createField9_0 = $$createType1;
        const $$createField13_0 = $$createType28;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField9_0($$parsedSource["metadata"]);
        }
        if ("history" in $$parsedSource) {
            $$parsedSource["history"] = $$createField13_0($$parsedSource["history"]);
        }
        return new WorkItemRun($$parsedSource as Partial<WorkItemRun>);
    }
}

export class WorkflowActionAvailability {
    "action": WorkflowActionDefinition;
    "enabled": boolean;
    "recommended": boolean;
    "reason"?: string;
    "inputKind": string;

    /** Creates a new WorkflowActionAvailability instance. */
    constructor($$source: Partial<WorkflowActionAvailability> = {}) {
        if (!("action" in $$source)) {
            this["action"] = (new WorkflowActionDefinition());
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("recommended" in $$source)) {
            this["recommended"] = false;
        }
        if (!("inputKind" in $$source)) {
            this["inputKind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkflowActionAvailability instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkflowActionAvailability {
        const $$createField0_0 = $$createType29;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("action" in $$parsedSource) {
            $$parsedSource["action"] = $$createField0_0($$parsedSource["action"]);
        }
        return new WorkflowActionAvailability($$parsedSource as Partial<WorkflowActionAvailability>);
    }
}

export class WorkflowActionDefinition {
    "id": string;
    "from": string[];
    "to": string;
    "requires"?: WorkflowArtifactRequirement[];
    "createsArtifact"?: WorkflowArtifactEffect | null;
    "updatesArtifact"?: WorkflowArtifactEffect | null;
    "createsRun"?: WorkflowRunEffect | null;
    "completesRun"?: boolean;
    "createsGates"?: string[];
    "resumesRun"?: string;
    "requiresPassingBlockingGates"?: boolean;
    "requiresHuman"?: boolean;
    "sideStage"?: boolean;

    /** Creates a new WorkflowActionDefinition instance. */
    constructor($$source: Partial<WorkflowActionDefinition> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("from" in $$source)) {
            this["from"] = [];
        }
        if (!("to" in $$source)) {
            this["to"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkflowActionDefinition instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkflowActionDefinition {
        const $$createField1_0 = $$createType20;
        const $$createField3_0 = $$createType31;
        const $$createField4_0 = $$createType33;
        const $$createField5_0 = $$createType33;
        const $$createField6_0 = $$createType35;
        const $$createField8_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("from" in $$parsedSource) {
            $$parsedSource["from"] = $$createField1_0($$parsedSource["from"]);
        }
        if ("requires" in $$parsedSource) {
            $$parsedSource["requires"] = $$createField3_0($$parsedSource["requires"]);
        }
        if ("createsArtifact" in $$parsedSource) {
            $$parsedSource["createsArtifact"] = $$createField4_0($$parsedSource["createsArtifact"]);
        }
        if ("updatesArtifact" in $$parsedSource) {
            $$parsedSource["updatesArtifact"] = $$createField5_0($$parsedSource["updatesArtifact"]);
        }
        if ("createsRun" in $$parsedSource) {
            $$parsedSource["createsRun"] = $$createField6_0($$parsedSource["createsRun"]);
        }
        if ("createsGates" in $$parsedSource) {
            $$parsedSource["createsGates"] = $$createField8_0($$parsedSource["createsGates"]);
        }
        return new WorkflowActionDefinition($$parsedSource as Partial<WorkflowActionDefinition>);
    }
}

export class WorkflowArtifactEffect {
    "kind": string;
    "status": string;

    /** Creates a new WorkflowArtifactEffect instance. */
    constructor($$source: Partial<WorkflowArtifactEffect> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkflowArtifactEffect instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkflowArtifactEffect {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkflowArtifactEffect($$parsedSource as Partial<WorkflowArtifactEffect>);
    }
}

export class WorkflowArtifactRequirement {
    "kind": string;
    "status": string;

    /** Creates a new WorkflowArtifactRequirement instance. */
    constructor($$source: Partial<WorkflowArtifactRequirement> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkflowArtifactRequirement instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkflowArtifactRequirement {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkflowArtifactRequirement($$parsedSource as Partial<WorkflowArtifactRequirement>);
    }
}

export class WorkflowDefinition {
    "id": string;
    "version": number;
    "stages": string[];
    "actions": WorkflowActionDefinition[];
    "questions": WorkflowQuestionPolicy;
    "gates": WorkflowGateDefinition[];

    /** Creates a new WorkflowDefinition instance. */
    constructor($$source: Partial<WorkflowDefinition> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("stages" in $$source)) {
            this["stages"] = [];
        }
        if (!("actions" in $$source)) {
            this["actions"] = [];
        }
        if (!("questions" in $$source)) {
            this["questions"] = (new WorkflowQuestionPolicy());
        }
        if (!("gates" in $$source)) {
            this["gates"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkflowDefinition instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkflowDefinition {
        const $$createField2_0 = $$createType20;
        const $$createField3_0 = $$createType36;
        const $$createField4_0 = $$createType37;
        const $$createField5_0 = $$createType39;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stages" in $$parsedSource) {
            $$parsedSource["stages"] = $$createField2_0($$parsedSource["stages"]);
        }
        if ("actions" in $$parsedSource) {
            $$parsedSource["actions"] = $$createField3_0($$parsedSource["actions"]);
        }
        if ("questions" in $$parsedSource) {
            $$parsedSource["questions"] = $$createField4_0($$parsedSource["questions"]);
        }
        if ("gates" in $$parsedSource) {
            $$parsedSource["gates"] = $$createField5_0($$parsedSource["gates"]);
        }
        return new WorkflowDefinition($$parsedSource as Partial<WorkflowDefinition>);
    }
}

export class WorkflowDefinitionRecord {
    "id": string;
    "version": number;
    "source": string;
    "sourcePath"?: string;
    "contentHash": string;
    "definition": WorkflowDefinition;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new WorkflowDefinitionRecord instance. */
    constructor($$source: Partial<WorkflowDefinitionRecord> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("contentHash" in $$source)) {
            this["contentHash"] = "";
        }
        if (!("definition" in $$source)) {
            this["definition"] = (new WorkflowDefinition());
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkflowDefinitionRecord instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkflowDefinitionRecord {
        const $$createField5_0 = $$createType40;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("definition" in $$parsedSource) {
            $$parsedSource["definition"] = $$createField5_0($$parsedSource["definition"]);
        }
        return new WorkflowDefinitionRecord($$parsedSource as Partial<WorkflowDefinitionRecord>);
    }
}

export class WorkflowEvent {
    "id": string;
    "projectId": string;
    "workItemId"?: string;
    "runId"?: string;
    "type": string;
    "actor"?: string;
    "message"?: string;
    "at": time$0.Time;

    /** Creates a new WorkflowEvent instance. */
    constructor($$source: Partial<WorkflowEvent> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("at" in $$source)) {
            this["at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkflowEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkflowEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkflowEvent($$parsedSource as Partial<WorkflowEvent>);
    }
}

export class WorkflowGateDefinition {
    "id": string;
    "phase": string;
    "blocking": boolean;

    /** Creates a new WorkflowGateDefinition instance. */
    constructor($$source: Partial<WorkflowGateDefinition> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("phase" in $$source)) {
            this["phase"] = "";
        }
        if (!("blocking" in $$source)) {
            this["blocking"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkflowGateDefinition instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkflowGateDefinition {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkflowGateDefinition($$parsedSource as Partial<WorkflowGateDefinition>);
    }
}

export class WorkflowMigrationItem {
    "workItemId": string;
    "number": number;
    "title": string;
    "currentWorkflowId": string;
    "currentWorkflowVersion": number;
    "currentStageId": string;
    "targetStageId"?: string;
    "compatible": boolean;
    "reason"?: string;

    /** Creates a new WorkflowMigrationItem instance. */
    constructor($$source: Partial<WorkflowMigrationItem> = {}) {
        if (!("workItemId" in $$source)) {
            this["workItemId"] = "";
        }
        if (!("number" in $$source)) {
            this["number"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("currentWorkflowId" in $$source)) {
            this["currentWorkflowId"] = "";
        }
        if (!("currentWorkflowVersion" in $$source)) {
            this["currentWorkflowVersion"] = 0;
        }
        if (!("currentStageId" in $$source)) {
            this["currentStageId"] = "";
        }
        if (!("compatible" in $$source)) {
            this["compatible"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkflowMigrationItem instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkflowMigrationItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkflowMigrationItem($$parsedSource as Partial<WorkflowMigrationItem>);
    }
}

export class WorkflowMigrationPlan {
    "projectId": string;
    "currentId": string;
    "currentVersion": number;
    "targetId": string;
    "targetVersion": number;
    "existingItems": number;
    "itemsPinnedToCurrentVersion": number;
    "compatibleItems": number;
    "incompatibleItems": number;
    "items": WorkflowMigrationItem[];

    /** Creates a new WorkflowMigrationPlan instance. */
    constructor($$source: Partial<WorkflowMigrationPlan> = {}) {
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("currentId" in $$source)) {
            this["currentId"] = "";
        }
        if (!("currentVersion" in $$source)) {
            this["currentVersion"] = 0;
        }
        if (!("targetId" in $$source)) {
            this["targetId"] = "";
        }
        if (!("targetVersion" in $$source)) {
            this["targetVersion"] = 0;
        }
        if (!("existingItems" in $$source)) {
            this["existingItems"] = 0;
        }
        if (!("itemsPinnedToCurrentVersion" in $$source)) {
            this["itemsPinnedToCurrentVersion"] = 0;
        }
        if (!("compatibleItems" in $$source)) {
            this["compatibleItems"] = 0;
        }
        if (!("incompatibleItems" in $$source)) {
            this["incompatibleItems"] = 0;
        }
        if (!("items" in $$source)) {
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkflowMigrationPlan instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkflowMigrationPlan {
        const $$createField9_0 = $$createType42;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField9_0($$parsedSource["items"]);
        }
        return new WorkflowMigrationPlan($$parsedSource as Partial<WorkflowMigrationPlan>);
    }
}

export class WorkflowQuestionPolicy {
    "enabled": boolean;
    "moveToBlocked": boolean;
    "setsRunState": string;
    "answerClearsAwaitingInputWhenNoOpenQuestionsRemain": boolean;

    /** Creates a new WorkflowQuestionPolicy instance. */
    constructor($$source: Partial<WorkflowQuestionPolicy> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("moveToBlocked" in $$source)) {
            this["moveToBlocked"] = false;
        }
        if (!("setsRunState" in $$source)) {
            this["setsRunState"] = "";
        }
        if (!("answerClearsAwaitingInputWhenNoOpenQuestionsRemain" in $$source)) {
            this["answerClearsAwaitingInputWhenNoOpenQuestionsRemain"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkflowQuestionPolicy instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkflowQuestionPolicy {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkflowQuestionPolicy($$parsedSource as Partial<WorkflowQuestionPolicy>);
    }
}

export class WorkflowRunEffect {
    "phase": string;
    "preset": string;
    "promptTemplateId": string;
    "workingDir": string;
    "autoProvisionWorktree"?: boolean;

    /** Creates a new WorkflowRunEffect instance. */
    constructor($$source: Partial<WorkflowRunEffect> = {}) {
        if (!("phase" in $$source)) {
            this["phase"] = "";
        }
        if (!("preset" in $$source)) {
            this["preset"] = "";
        }
        if (!("promptTemplateId" in $$source)) {
            this["promptTemplateId"] = "";
        }
        if (!("workingDir" in $$source)) {
            this["workingDir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkflowRunEffect instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkflowRunEffect {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkflowRunEffect($$parsedSource as Partial<WorkflowRunEffect>);
    }
}

export class WorkflowStage {
    "id": string;
    "name": string;
    "kind": string;
    "defaultRunPreset"?: string;
    "defaultPromptTemplateId"?: string;
    "provisionWorktree"?: boolean;
    "wipLimit"?: number;

    /** Creates a new WorkflowStage instance. */
    constructor($$source: Partial<WorkflowStage> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkflowStage instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkflowStage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkflowStage($$parsedSource as Partial<WorkflowStage>);
    }
}

export class WorkflowTemplate {
    "id": string;
    "name": string;
    "source": string;
    "stages": WorkflowStage[];
    "transitionRules": TransitionRule[];
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new WorkflowTemplate instance. */
    constructor($$source: Partial<WorkflowTemplate> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("stages" in $$source)) {
            this["stages"] = [];
        }
        if (!("transitionRules" in $$source)) {
            this["transitionRules"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkflowTemplate instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkflowTemplate {
        const $$createField3_0 = $$createType13;
        const $$createField4_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stages" in $$parsedSource) {
            $$parsedSource["stages"] = $$createField3_0($$parsedSource["stages"]);
        }
        if ("transitionRules" in $$parsedSource) {
            $$parsedSource["transitionRules"] = $$createField4_0($$parsedSource["transitionRules"]);
        }
        return new WorkflowTemplate($$parsedSource as Partial<WorkflowTemplate>);
    }
}

export class WorkflowValidationError {
    "path"?: string;
    "message": string;

    /** Creates a new WorkflowValidationError instance. */
    constructor($$source: Partial<WorkflowValidationError> = {}) {
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkflowValidationError instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkflowValidationError {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkflowValidationError($$parsedSource as Partial<WorkflowValidationError>);
    }
}

export class WorkflowValidationReport {
    "valid": boolean;
    "identity"?: string;
    "errors"?: WorkflowValidationError[];

    /** Creates a new WorkflowValidationReport instance. */
    constructor($$source: Partial<WorkflowValidationReport> = {}) {
        if (!("valid" in $$source)) {
            this["valid"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkflowValidationReport instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkflowValidationReport {
        const $$createField2_0 = $$createType44;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField2_0($$parsedSource["errors"]);
        }
        return new WorkflowValidationReport($$parsedSource as Partial<WorkflowValidationReport>);
    }
}

export class WorktreeBinding {
    "branch": string;
    "base": string;
    "worktreePath": string;
    "createdAt": time$0.Time;

    /** Creates a new WorktreeBinding instance. */
    constructor($$source: Partial<WorktreeBinding> = {}) {
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("base" in $$source)) {
            this["base"] = "";
        }
        if (!("worktreePath" in $$source)) {
            this["worktreePath"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorktreeBinding instance from a string or object.
     */
    static createFrom($$source: any = {}): WorktreeBinding {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorktreeBinding($$parsedSource as Partial<WorktreeBinding>);
    }
}

// Private type creation functions
const $$createType0 = MetadataValue.createFrom;
const $$createType1 = $Create.Map($Create.Any, $$createType0);
const $$createType2 = WorkItem.createFrom;
const $$createType3 = ReadyBlockerInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = ProjectWorkflow.createFrom;
const $$createType6 = ProjectPreferences.createFrom;
const $$createType7 = Attachment.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Map($Create.Any, $Create.Any);
const $$createType10 = GateConfig.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = WorkflowStage.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = TransitionRule.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = ReadyWorkItem.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = BlockedWorkItem.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = $Create.Array($Create.Any);
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = ReadyWorkSummary.createFrom;
const $$createType23 = WorktreeBinding.createFrom;
const $$createType24 = $Create.Nullable($$createType23);
const $$createType25 = HistoryEvent.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = RunEvent.createFrom;
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = WorkflowActionDefinition.createFrom;
const $$createType30 = WorkflowArtifactRequirement.createFrom;
const $$createType31 = $Create.Array($$createType30);
const $$createType32 = WorkflowArtifactEffect.createFrom;
const $$createType33 = $Create.Nullable($$createType32);
const $$createType34 = WorkflowRunEffect.createFrom;
const $$createType35 = $Create.Nullable($$createType34);
const $$createType36 = $Create.Array($$createType29);
const $$createType37 = WorkflowQuestionPolicy.createFrom;
const $$createType38 = WorkflowGateDefinition.createFrom;
const $$createType39 = $Create.Array($$createType38);
const $$createType40 = WorkflowDefinition.createFrom;
const $$createType41 = WorkflowMigrationItem.createFrom;
const $$createType42 = $Create.Array($$createType41);
const $$createType43 = WorkflowValidationError.createFrom;
const $$createType44 = $Create.Array($$createType43);
