// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

export class Artifact {
    "id": string;
    "projectId": string;
    "workItemId": string;
    "runId"?: string;
    "kind": string;
    "status": string;
    "title"?: string;
    "body"?: string;
    "metadata"?: { [_ in string]?: MetadataValue };
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new Artifact instance. */
    constructor($$source: Partial<Artifact> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("workItemId" in $$source)) {
            this["workItemId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Artifact instance from a string or object.
     */
    static createFrom($$source: any = {}): Artifact {
        const $$createField8_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField8_0($$parsedSource["metadata"]);
        }
        return new Artifact($$parsedSource as Partial<Artifact>);
    }
}

export class Attachment {
    "id": string;
    "kind": string;
    "scope": string;
    "path"?: string;
    "url"?: string;
    "note"?: string;
    "createdAt": time$0.Time;

    /** Creates a new Attachment instance. */
    constructor($$source: Partial<Attachment> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("scope" in $$source)) {
            this["scope"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Attachment instance from a string or object.
     */
    static createFrom($$source: any = {}): Attachment {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Attachment($$parsedSource as Partial<Attachment>);
    }
}

export class GateConfig {
    "id": string;
    "name": string;
    "kind": string;
    "command"?: string;
    "skill"?: string;
    "blocking": boolean;
    "phase"?: string;

    /** Creates a new GateConfig instance. */
    constructor($$source: Partial<GateConfig> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("blocking" in $$source)) {
            this["blocking"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GateConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): GateConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GateConfig($$parsedSource as Partial<GateConfig>);
    }
}

export class GateReport {
    "id": string;
    "projectId": string;
    "workItemId": string;
    "runId"?: string;
    "name": string;
    "blocking": boolean;
    "status": string;
    "overrideReason"?: string;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new GateReport instance. */
    constructor($$source: Partial<GateReport> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("workItemId" in $$source)) {
            this["workItemId"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("blocking" in $$source)) {
            this["blocking"] = false;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GateReport instance from a string or object.
     */
    static createFrom($$source: any = {}): GateReport {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GateReport($$parsedSource as Partial<GateReport>);
    }
}

export class HistoryEvent {
    "id": string;
    "type": string;
    "at": time$0.Time;
    "actor"?: string;
    "message"?: string;
    "stageId"?: string;
    "attachmentId"?: string;
    "branch"?: string;
    "worktreePath"?: string;

    /** Creates a new HistoryEvent instance. */
    constructor($$source: Partial<HistoryEvent> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("at" in $$source)) {
            this["at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryEvent($$parsedSource as Partial<HistoryEvent>);
    }
}

export class MetadataValue {
    "type": string;
    "string"?: string;
    "number"?: number;
    "bool"?: boolean;
    "json"?: json$0.RawMessage;

    /** Creates a new MetadataValue instance. */
    constructor($$source: Partial<MetadataValue> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MetadataValue instance from a string or object.
     */
    static createFrom($$source: any = {}): MetadataValue {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MetadataValue($$parsedSource as Partial<MetadataValue>);
    }
}

export class Project {
    "id": string;
    "name": string;
    "description"?: string;
    "slug": string;
    "rootDir": string;
    "workflow": ProjectWorkflow;
    "preferences": ProjectPreferences;
    "metadata"?: { [_ in string]?: MetadataValue };
    "nextWorkItemNumber": number;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new Project instance. */
    constructor($$source: Partial<Project> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("slug" in $$source)) {
            this["slug"] = "";
        }
        if (!("rootDir" in $$source)) {
            this["rootDir"] = "";
        }
        if (!("workflow" in $$source)) {
            this["workflow"] = (new ProjectWorkflow());
        }
        if (!("preferences" in $$source)) {
            this["preferences"] = (new ProjectPreferences());
        }
        if (!("nextWorkItemNumber" in $$source)) {
            this["nextWorkItemNumber"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Project instance from a string or object.
     */
    static createFrom($$source: any = {}): Project {
        const $$createField5_0 = $$createType2;
        const $$createField6_0 = $$createType3;
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("workflow" in $$parsedSource) {
            $$parsedSource["workflow"] = $$createField5_0($$parsedSource["workflow"]);
        }
        if ("preferences" in $$parsedSource) {
            $$parsedSource["preferences"] = $$createField6_0($$parsedSource["preferences"]);
        }
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField7_0($$parsedSource["metadata"]);
        }
        return new Project($$parsedSource as Partial<Project>);
    }
}

export class ProjectPreferences {
    "autoRun": string;
    "autoWorktree": boolean;
    "defaultPhaseAgents"?: { [_ in string]?: string };
    "gates"?: GateConfig[];

    /** Creates a new ProjectPreferences instance. */
    constructor($$source: Partial<ProjectPreferences> = {}) {
        if (!("autoRun" in $$source)) {
            this["autoRun"] = "";
        }
        if (!("autoWorktree" in $$source)) {
            this["autoWorktree"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectPreferences instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectPreferences {
        const $$createField2_0 = $$createType4;
        const $$createField3_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("defaultPhaseAgents" in $$parsedSource) {
            $$parsedSource["defaultPhaseAgents"] = $$createField2_0($$parsedSource["defaultPhaseAgents"]);
        }
        if ("gates" in $$parsedSource) {
            $$parsedSource["gates"] = $$createField3_0($$parsedSource["gates"]);
        }
        return new ProjectPreferences($$parsedSource as Partial<ProjectPreferences>);
    }
}

export class ProjectWorkflow {
    "id": string;
    "templateId": string;
    "name": string;
    "stages": WorkflowStage[];
    "transitionRules": TransitionRule[];

    /** Creates a new ProjectWorkflow instance. */
    constructor($$source: Partial<ProjectWorkflow> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("templateId" in $$source)) {
            this["templateId"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("stages" in $$source)) {
            this["stages"] = [];
        }
        if (!("transitionRules" in $$source)) {
            this["transitionRules"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectWorkflow instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectWorkflow {
        const $$createField3_0 = $$createType8;
        const $$createField4_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stages" in $$parsedSource) {
            $$parsedSource["stages"] = $$createField3_0($$parsedSource["stages"]);
        }
        if ("transitionRules" in $$parsedSource) {
            $$parsedSource["transitionRules"] = $$createField4_0($$parsedSource["transitionRules"]);
        }
        return new ProjectWorkflow($$parsedSource as Partial<ProjectWorkflow>);
    }
}

export class PromptTemplate {
    "id": string;
    "name": string;
    "source": string;
    "body": string;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new PromptTemplate instance. */
    constructor($$source: Partial<PromptTemplate> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PromptTemplate instance from a string or object.
     */
    static createFrom($$source: any = {}): PromptTemplate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PromptTemplate($$parsedSource as Partial<PromptTemplate>);
    }
}

export class Question {
    "id": string;
    "projectId": string;
    "workItemId": string;
    "runId"?: string;
    "sessionId"?: string;
    "ptyId"?: string;
    "prompt": string;
    "answer"?: string;
    "status": string;
    "actor"?: string;
    "answeredBy"?: string;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;
    "answeredAt"?: time$0.Time | null;

    /** Creates a new Question instance. */
    constructor($$source: Partial<Question> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("workItemId" in $$source)) {
            this["workItemId"] = "";
        }
        if (!("prompt" in $$source)) {
            this["prompt"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Question instance from a string or object.
     */
    static createFrom($$source: any = {}): Question {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Question($$parsedSource as Partial<Question>);
    }
}

export class RunEvent {
    "id": string;
    "type": string;
    "at": time$0.Time;
    "actor"?: string;
    "message"?: string;

    /** Creates a new RunEvent instance. */
    constructor($$source: Partial<RunEvent> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("at" in $$source)) {
            this["at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): RunEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RunEvent($$parsedSource as Partial<RunEvent>);
    }
}

export class StatusEvent {
    "id": string;
    "scope": string;
    "kind": string;
    "message": string;
    "actor"?: string;
    "projectId"?: string;
    "workItemId"?: string;
    "runId"?: string;
    "sessionId"?: string;
    "ptyId"?: string;
    "requiresAttention": boolean;
    "createdAt": time$0.Time;
    "readAt"?: time$0.Time | null;

    /** Creates a new StatusEvent instance. */
    constructor($$source: Partial<StatusEvent> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("scope" in $$source)) {
            this["scope"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("requiresAttention" in $$source)) {
            this["requiresAttention"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatusEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): StatusEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StatusEvent($$parsedSource as Partial<StatusEvent>);
    }
}

export class TransitionRule {
    "fromStageId": string;
    "toStageId": string;
    "requiresApproval"?: boolean;
    "requiresChecks"?: boolean;
    "requiresNoRunningRuns"?: boolean;

    /** Creates a new TransitionRule instance. */
    constructor($$source: Partial<TransitionRule> = {}) {
        if (!("fromStageId" in $$source)) {
            this["fromStageId"] = "";
        }
        if (!("toStageId" in $$source)) {
            this["toStageId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TransitionRule instance from a string or object.
     */
    static createFrom($$source: any = {}): TransitionRule {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TransitionRule($$parsedSource as Partial<TransitionRule>);
    }
}

export class WorkItem {
    "id": string;
    "projectId": string;
    "workflowId": string;
    "workflowVersion": number;
    "number": number;
    "title": string;
    "bodyMarkdown": string;
    "stageId": string;
    "previousStageId"?: string;
    "runState": string;
    "worktree"?: WorktreeBinding | null;
    "attachments": Attachment[];
    "metadata"?: { [_ in string]?: MetadataValue };
    "history": HistoryEvent[];
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new WorkItem instance. */
    constructor($$source: Partial<WorkItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("workflowId" in $$source)) {
            this["workflowId"] = "";
        }
        if (!("workflowVersion" in $$source)) {
            this["workflowVersion"] = 0;
        }
        if (!("number" in $$source)) {
            this["number"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("bodyMarkdown" in $$source)) {
            this["bodyMarkdown"] = "";
        }
        if (!("stageId" in $$source)) {
            this["stageId"] = "";
        }
        if (!("runState" in $$source)) {
            this["runState"] = "";
        }
        if (!("attachments" in $$source)) {
            this["attachments"] = [];
        }
        if (!("history" in $$source)) {
            this["history"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkItem instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkItem {
        const $$createField10_0 = $$createType12;
        const $$createField11_0 = $$createType14;
        const $$createField12_0 = $$createType1;
        const $$createField13_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("worktree" in $$parsedSource) {
            $$parsedSource["worktree"] = $$createField10_0($$parsedSource["worktree"]);
        }
        if ("attachments" in $$parsedSource) {
            $$parsedSource["attachments"] = $$createField11_0($$parsedSource["attachments"]);
        }
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField12_0($$parsedSource["metadata"]);
        }
        if ("history" in $$parsedSource) {
            $$parsedSource["history"] = $$createField13_0($$parsedSource["history"]);
        }
        return new WorkItem($$parsedSource as Partial<WorkItem>);
    }
}

export class WorkItemRun {
    "id": string;
    "workItemId": string;
    "projectId": string;
    "preset": string;
    "promptTemplateId": string;
    "promptSnapshot": string;
    "sessionId"?: string;
    "ptyId"?: string;
    "status": string;
    "metadata"?: { [_ in string]?: MetadataValue };
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;
    "completedAt"?: time$0.Time | null;
    "history": RunEvent[];

    /** Creates a new WorkItemRun instance. */
    constructor($$source: Partial<WorkItemRun> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("workItemId" in $$source)) {
            this["workItemId"] = "";
        }
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("preset" in $$source)) {
            this["preset"] = "";
        }
        if (!("promptTemplateId" in $$source)) {
            this["promptTemplateId"] = "";
        }
        if (!("promptSnapshot" in $$source)) {
            this["promptSnapshot"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }
        if (!("history" in $$source)) {
            this["history"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkItemRun instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkItemRun {
        const $$createField9_0 = $$createType1;
        const $$createField13_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField9_0($$parsedSource["metadata"]);
        }
        if ("history" in $$parsedSource) {
            $$parsedSource["history"] = $$createField13_0($$parsedSource["history"]);
        }
        return new WorkItemRun($$parsedSource as Partial<WorkItemRun>);
    }
}

export class WorkflowEvent {
    "id": string;
    "projectId": string;
    "workItemId"?: string;
    "runId"?: string;
    "type": string;
    "actor"?: string;
    "message"?: string;
    "at": time$0.Time;

    /** Creates a new WorkflowEvent instance. */
    constructor($$source: Partial<WorkflowEvent> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("at" in $$source)) {
            this["at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkflowEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkflowEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkflowEvent($$parsedSource as Partial<WorkflowEvent>);
    }
}

export class WorkflowStage {
    "id": string;
    "name": string;
    "kind": string;
    "defaultRunPreset"?: string;
    "defaultPromptTemplateId"?: string;
    "provisionWorktree"?: boolean;
    "wipLimit"?: number;

    /** Creates a new WorkflowStage instance. */
    constructor($$source: Partial<WorkflowStage> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkflowStage instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkflowStage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkflowStage($$parsedSource as Partial<WorkflowStage>);
    }
}

export class WorkflowTemplate {
    "id": string;
    "name": string;
    "source": string;
    "stages": WorkflowStage[];
    "transitionRules": TransitionRule[];
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new WorkflowTemplate instance. */
    constructor($$source: Partial<WorkflowTemplate> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("stages" in $$source)) {
            this["stages"] = [];
        }
        if (!("transitionRules" in $$source)) {
            this["transitionRules"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkflowTemplate instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkflowTemplate {
        const $$createField3_0 = $$createType8;
        const $$createField4_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stages" in $$parsedSource) {
            $$parsedSource["stages"] = $$createField3_0($$parsedSource["stages"]);
        }
        if ("transitionRules" in $$parsedSource) {
            $$parsedSource["transitionRules"] = $$createField4_0($$parsedSource["transitionRules"]);
        }
        return new WorkflowTemplate($$parsedSource as Partial<WorkflowTemplate>);
    }
}

export class WorktreeBinding {
    "branch": string;
    "base": string;
    "worktreePath": string;
    "createdAt": time$0.Time;

    /** Creates a new WorktreeBinding instance. */
    constructor($$source: Partial<WorktreeBinding> = {}) {
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("base" in $$source)) {
            this["base"] = "";
        }
        if (!("worktreePath" in $$source)) {
            this["worktreePath"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorktreeBinding instance from a string or object.
     */
    static createFrom($$source: any = {}): WorktreeBinding {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorktreeBinding($$parsedSource as Partial<WorktreeBinding>);
    }
}

// Private type creation functions
const $$createType0 = MetadataValue.createFrom;
const $$createType1 = $Create.Map($Create.Any, $$createType0);
const $$createType2 = ProjectWorkflow.createFrom;
const $$createType3 = ProjectPreferences.createFrom;
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = GateConfig.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = WorkflowStage.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = TransitionRule.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = WorktreeBinding.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = Attachment.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = HistoryEvent.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = RunEvent.createFrom;
const $$createType18 = $Create.Array($$createType17);
