package client

import (
	"context"

	"github.com/phin-tech/whisk/internal/domain/session"
	"github.com/phin-tech/whisk/internal/protocol"
)

type RuntimeClient interface {
	ClearDaemon(ctx context.Context, req protocol.ClearDaemonRequest) (protocol.ClearDaemonResponse, error)
	OnboardingStatus(ctx context.Context) (protocol.OnboardingStatus, error)
	ApplyOnboarding(ctx context.Context, req protocol.OnboardingApplyRequest) (protocol.OnboardingStatus, error)
	AgentBridgeHook(ctx context.Context, bridgeID string, req protocol.AgentBridgeHookRequest) (protocol.AgentBridgeHookResponse, error)
	RecordAgentHookEvent(ctx context.Context, req protocol.AgentBridgeHookRequest) (protocol.AgentBridgeEvent, error)
	ListAgentBridgeApprovals(ctx context.Context, req protocol.ListAgentBridgeApprovalsRequest) ([]protocol.AgentBridgeApproval, error)
	ResolveAgentBridgeApproval(ctx context.Context, id string, req protocol.ResolveAgentBridgeApprovalRequest) (protocol.AgentBridgeApproval, error)
	ListAgentPrompts(ctx context.Context, req protocol.ListAgentPromptsRequest) ([]protocol.AgentPrompt, error)
	ResolveAgentPrompt(ctx context.Context, id string, req protocol.ResolveAgentPromptRequest) (protocol.AgentPrompt, error)
	ListAgentBridgeEvents(ctx context.Context, req protocol.ListAgentBridgeEventsRequest) ([]protocol.AgentBridgeEvent, error)
	MarkAgentBridgeEventRead(ctx context.Context, req protocol.MarkAgentBridgeEventReadRequest) (protocol.AgentBridgeEvent, error)
	ListAgentHookIntegrations(ctx context.Context) ([]protocol.AgentHookIntegration, error)
	CheckAgentHookIntegration(ctx context.Context, req protocol.AgentHookIntegrationRequest) (protocol.AgentHookIntegration, error)
	InstallAgentHookIntegration(ctx context.Context, req protocol.AgentHookIntegrationRequest) (protocol.AgentHookIntegration, error)
	RemoveAgentHookIntegration(ctx context.Context, req protocol.AgentHookIntegrationRequest) (protocol.AgentHookIntegration, error)
	AgentHookLogStatus(ctx context.Context) (protocol.AgentHookLogStatus, error)
	SetAgentHookLogSettings(ctx context.Context, req protocol.SetAgentHookLogSettingsRequest) (protocol.AgentHookLogStatus, error)
	ClearAgentHookLog(ctx context.Context) (protocol.AgentHookLogStatus, error)
	OpenAgentHookLog(ctx context.Context) (protocol.AgentHookLogStatus, error)
	ListPlugins(ctx context.Context) ([]protocol.PluginStatus, error)
	ListUIContributions(ctx context.Context, scope protocol.UIContributionScope) (protocol.UIContributionsResponse, error)
	RescanPlugins(ctx context.Context) ([]protocol.PluginStatus, error)
	TrustPlugin(ctx context.Context, id string) (protocol.PluginStatus, error)
	UntrustPlugin(ctx context.Context, id string) (protocol.PluginStatus, error)
	ListRegistryPlugins(ctx context.Context) ([]protocol.RegistryPlugin, error)
	InstallPlugin(ctx context.Context, registry, id string) (protocol.PluginStatus, error)
	RunPluginProjectAttachmentTemplate(ctx context.Context, pluginID string, templateID string, req protocol.RunPluginProjectAttachmentTemplateRequest) (protocol.Project, error)
	ListSessions(ctx context.Context) ([]session.Session, error)
	CreateSession(ctx context.Context, req protocol.CreateSessionRequest) (protocol.CreatedSession, error)
	SplitPane(ctx context.Context, req protocol.SplitPaneRequest) (protocol.SplitPaneResult, error)
	SetSessionRootDir(ctx context.Context, req protocol.SetSessionRootDirRequest) (session.Session, error)
	SetSessionProject(ctx context.Context, req protocol.SetSessionProjectRequest) (session.Session, error)
	SetPaneWorkingDir(ctx context.Context, req protocol.SetPaneWorkingDirRequest) (session.Session, error)
	StartPanePTY(ctx context.Context, req protocol.StartPanePTYRequest) (protocol.StartedPanePTY, error)
	RestartPanePTY(ctx context.Context, req protocol.RestartPanePTYRequest) (protocol.RestartedPanePTY, error)
	DetachPanePTY(ctx context.Context, req protocol.DetachPanePTYRequest) (protocol.DetachedPanePTY, error)
	CloseSession(ctx context.Context, req protocol.CloseSessionRequest) ([]session.Session, error)
	ClosePane(ctx context.Context, req protocol.ClosePaneRequest) (session.Session, error)
	KillPTY(ctx context.Context, req protocol.KillPTYRequest) (protocol.PTYInfo, error)
	DeletePTY(ctx context.Context, req protocol.DeletePTYRequest) error
	WritePTY(ctx context.Context, req protocol.WritePTYRequest) error
	ResizePTY(ctx context.Context, req protocol.ResizePTYRequest) error
	Output(ctx context.Context, req protocol.OutputRequest) (protocol.OutputSnapshot, error)
	ListPTYs(ctx context.Context) ([]protocol.PTYInfo, error)
	ListPTYHistory(ctx context.Context) ([]protocol.PTYHistorySummary, error)
	ReadPTYHistory(ctx context.Context, ptyID string) (protocol.PTYHistory, error)
	NextEvent(ctx context.Context, req protocol.NextEventRequest) (protocol.NextEventResponse, error)
	SendMail(ctx context.Context, req protocol.SendMailRequest) (protocol.MailMessage, error)
	ListMail(ctx context.Context, req protocol.ListMailRequest) ([]protocol.MailMessage, error)
	NextMail(ctx context.Context, req protocol.NextMailRequest) (protocol.NextMailResponse, error)
	MarkMailRead(ctx context.Context, mailID string, req protocol.MarkMailReadRequest) (protocol.MailMessage, error)
	ReplyMail(ctx context.Context, mailID string, req protocol.ReplyMailRequest) (protocol.MailMessage, error)
	DetectWorktrunk(ctx context.Context, req protocol.DetectWorktrunkRequest) (protocol.WorktrunkStatus, error)
	ListWorktrees(ctx context.Context, req protocol.ListWorktreesRequest) ([]protocol.Worktree, error)
	CreateWorktree(ctx context.Context, req protocol.CreateWorktreeRequest) (protocol.CreatedWorktree, error)
	RemoveWorktree(ctx context.Context, req protocol.RemoveWorktreeRequest) error
	ListProjects(ctx context.Context) ([]protocol.Project, error)
	CreateProject(ctx context.Context, req protocol.CreateProjectRequest) (protocol.Project, error)
	UpdateProject(ctx context.Context, projectID string, req protocol.UpdateProjectRequest) (protocol.Project, error)
	DeleteProject(ctx context.Context, projectID string, req protocol.DeleteProjectRequest) (protocol.Project, error)
	GetProjectDetail(ctx context.Context, projectID string) (protocol.ProjectDetail, error)
	SetProjectWorkflowDefinition(ctx context.Context, projectID string, req protocol.SetProjectWorkflowDefinitionRequest) (protocol.Project, error)
	PlanProjectWorkflowMigration(ctx context.Context, projectID string, req protocol.PlanProjectWorkflowMigrationRequest) (protocol.WorkflowMigrationPlan, error)
	AddProjectAttachment(ctx context.Context, req protocol.AddProjectAttachmentRequest) (protocol.Project, error)
	UpdateProjectAttachment(ctx context.Context, attachmentID string, req protocol.UpdateProjectAttachmentRequest) (protocol.Project, error)
	DeleteProjectAttachment(ctx context.Context, attachmentID string, req protocol.DeleteProjectAttachmentRequest) (protocol.Project, error)
	GetProjectContext(ctx context.Context, projectID string) (protocol.ProjectContext, error)
	ListWorkflowTemplates(ctx context.Context) ([]protocol.WorkflowTemplate, error)
	ListWorkflowDefinitions(ctx context.Context) ([]protocol.WorkflowDefinitionRecord, error)
	ValidateWorkflowDefinition(ctx context.Context, req protocol.ValidateWorkflowDefinitionRequest) (protocol.WorkflowValidationReport, error)
	ValidateWorkflowDefinitionFile(ctx context.Context, req protocol.ValidateWorkflowDefinitionFileRequest) (protocol.WorkflowValidationReport, error)
	ImportWorkflowDefinition(ctx context.Context, req protocol.ImportWorkflowDefinitionRequest) (protocol.WorkflowDefinitionRecord, error)
	ImportWorkflowDefinitionFile(ctx context.Context, req protocol.ImportWorkflowDefinitionFileRequest) (protocol.WorkflowDefinitionRecord, error)
	ExportWorkflowDefinitionFile(ctx context.Context, req protocol.ExportWorkflowDefinitionFileRequest) error
	DeleteWorkflowDefinition(ctx context.Context, id string, version int) (protocol.WorkflowDefinitionRecord, error)
	ListPromptTemplates(ctx context.Context) ([]protocol.PromptTemplate, error)
	ListAgentProfiles(ctx context.Context) ([]protocol.AgentProfile, error)
	ListDetectedAgents(ctx context.Context) ([]protocol.DetectedAgent, error)
	ListWorkItems(ctx context.Context, projectID string) ([]protocol.WorkItem, error)
	CreateWorkItem(ctx context.Context, req protocol.CreateWorkItemRequest) (protocol.WorkItem, error)
	UpdateWorkItem(ctx context.Context, req protocol.UpdateWorkItemRequest) (protocol.WorkItem, error)
	MoveWorkItem(ctx context.Context, req protocol.MoveWorkItemRequest) (protocol.WorkItem, error)
	ListWorkItemWorkflowActions(ctx context.Context, workItemID string) ([]protocol.WorkflowActionAvailability, error)
	AddWorkItemLink(ctx context.Context, req protocol.AddWorkItemLinkRequest) (protocol.WorkItemLink, error)
	ListWorkItemLinks(ctx context.Context, workItemID string) ([]protocol.WorkItemLink, error)
	ReadyWork(ctx context.Context, req protocol.ReadyWorkRequest) (protocol.ReadyWorkExplanation, error)
	StartPlanning(ctx context.Context, req protocol.StartPlanningRequest) (protocol.WorkItemRun, error)
	SubmitDraftPlan(ctx context.Context, req protocol.SubmitDraftPlanRequest) (protocol.Artifact, error)
	ApprovePlan(ctx context.Context, req protocol.ApprovePlanRequest) (protocol.WorkItem, error)
	StartExecution(ctx context.Context, req protocol.StartExecutionRequest) (protocol.WorkItemRun, error)
	QueueExecution(ctx context.Context, req protocol.QueueExecutionRequest) (protocol.WorkItemRun, error)
	LaunchExecution(ctx context.Context, req protocol.LaunchExecutionRequest) (protocol.WorkItemRun, error)
	AskQuestion(ctx context.Context, req protocol.AskQuestionRequest) (protocol.Question, error)
	AnswerQuestion(ctx context.Context, req protocol.AnswerQuestionRequest) (protocol.Question, error)
	CompleteExecution(ctx context.Context, req protocol.CompleteExecutionRequest) (protocol.WorkItem, error)
	SubmitReviewFeedback(ctx context.Context, req protocol.SubmitReviewFeedbackRequest) (protocol.Artifact, error)
	BindWorkItemWorktree(ctx context.Context, req protocol.BindWorkItemWorktreeRequest) (protocol.WorkItem, error)
	AddWorkItemAttachment(ctx context.Context, req protocol.AddWorkItemAttachmentRequest) (protocol.WorkItem, error)
	DeleteWorkItem(ctx context.Context, req protocol.DeleteWorkItemRequest) (protocol.WorkItem, error)
	ListWorkItemRuns(ctx context.Context, workItemID string) ([]protocol.WorkItemRun, error)
	StartWorkItemRun(ctx context.Context, req protocol.StartWorkItemRunRequest) (protocol.WorkItemRun, error)
	LaunchWorkItemRun(ctx context.Context, req protocol.LaunchWorkItemRunRequest) (protocol.WorkItemRun, error)
	CancelWorkItemRun(ctx context.Context, req protocol.CancelWorkItemRunRequest) (protocol.WorkItemRun, error)
	ApproveDone(ctx context.Context, req protocol.ApproveDoneRequest) (protocol.WorkItem, error)
	ListArtifacts(ctx context.Context, workItemID string) ([]protocol.Artifact, error)
	ListQuestions(ctx context.Context, workItemID string) ([]protocol.Question, error)
	ListGateReports(ctx context.Context, workItemID string) ([]protocol.GateReport, error)
	CompleteGate(ctx context.Context, req protocol.CompleteGateRequest) (protocol.GateReport, error)
	ListWorkflowEvents(ctx context.Context, workItemID string) ([]protocol.WorkflowEvent, error)
	ReportStatus(ctx context.Context, req protocol.ReportStatusRequest) (protocol.ReportStatusResponse, error)
	ListStatusEvents(ctx context.Context, req protocol.ListStatusEventsRequest) ([]protocol.StatusEvent, error)
	MarkStatusEventRead(ctx context.Context, req protocol.MarkStatusEventReadRequest) (protocol.StatusEvent, error)
	CreateHTTPForward(ctx context.Context, req protocol.CreateHTTPForwardRequest) (protocol.HTTPForward, error)
	ListHTTPForwards(ctx context.Context) ([]protocol.HTTPForward, error)
	DeleteHTTPForward(ctx context.Context, id string) error
}
