/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/compat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daemon API version and git SHA */
        get: operations["getCompatibility"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["nextEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/http-forwards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listHTTPForwards"];
        put?: never;
        post: operations["createHTTPForward"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/http-forwards/{forwardID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteHTTPForward"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProjects"];
        put?: never;
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/prompt-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPromptTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pty-bookmarks/{bookmarkID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removePTYBookmark"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ptys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPTYs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ptys/{ptyID}/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPTYBookmarks"];
        put?: never;
        post: operations["addPTYBookmark"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ptys/{ptyID}/kill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["killPTY"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ptys/{ptyID}/output": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPTYOutput"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ptys/{ptyID}/resize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resizePTY"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ptys/{ptyID}/write": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["writePTY"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSessions"];
        put?: never;
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["closeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionID}/panes/{paneID}/detach-pty": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["detachPanePTY"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionID}/panes/{paneID}/restart-pty": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restartPanePTY"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionID}/panes/{paneID}/set-working-dir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["setPaneWorkingDir"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionID}/panes/{paneID}/start-pty": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startPanePTY"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionID}/set-root-dir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["setSessionRootDir"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionID}/split": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["splitPane"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionID}/windows/{windowID}/panes/{paneID}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["closePane"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reportStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/status-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listStatusEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/status-events/{statusEventID}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["markStatusEventRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/work-item-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWorkItemRuns"];
        put?: never;
        post: operations["startWorkItemRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/work-item-runs/{runID}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelWorkItemRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/work-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWorkItems"];
        put?: never;
        post: operations["createWorkItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/work-items/{workItemID}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addWorkItemAttachment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/work-items/{workItemID}/bind-worktree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["bindWorkItemWorktree"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/work-items/{workItemID}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deleteWorkItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/work-items/{workItemID}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["moveWorkItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workflow-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWorkflowTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/worktrees/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createWorktree"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/worktrees/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["listWorktrees"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/worktrees/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["removeWorktree"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/worktrunk/detect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["detectWorktrunk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddPTYBookmarkRequest: {
            kind: string;
            label: string;
            /** Format: int64 */
            offset: number;
            ptyId: string;
        };
        AddWorkItemAttachmentRequest: {
            actor?: string;
            kind: string;
            note?: string;
            path?: string;
            scope?: string;
            url?: string;
            workItemId: string;
        };
        Attachment: {
            /** Format: date-time */
            createdAt: string;
            id: string;
            kind: string;
            note?: string;
            path?: string;
            scope: string;
            url?: string;
        };
        BindWorkItemWorktreeRequest: {
            actor?: string;
            base?: string;
            branch: string;
            id: string;
            worktreePath: string;
        };
        Bookmark: {
            /** Format: date-time */
            createdAt: string;
            id: string;
            kind: string;
            label: string;
            /** Format: int64 */
            offset: number;
            paneId: string;
            ptyId: string;
            sessionId: string;
            windowId: string;
        };
        CancelWorkItemRunRequest: {
            actor?: string;
            id: string;
        };
        ClosePaneRequest: {
            paneId: string;
            sessionId: string;
            windowId: string;
        };
        CompatibilityResponse: {
            /** Format: int64 */
            apiVersion: number;
            gitSha: string;
        };
        CreateHTTPForwardRequest: {
            name: string;
            sessionId: string;
            targetUrl: string;
        };
        CreateProjectRequest: {
            name: string;
            rootDir: string;
            slug?: string;
            workflowId?: string;
        };
        CreateSessionRequest: {
            initialPty?: components["schemas"]["StartPTYOptions"] | null;
            name: string;
            rootDir: string;
        };
        CreateWorkItemRequest: {
            actor?: string;
            bodyMarkdown?: string;
            projectId: string;
            stageId?: string;
            title: string;
        };
        CreateWorktreeRequest: {
            base: string;
            branch: string;
            repoPath: string;
        };
        CreatedSession: {
            mainPtyId?: string;
            paneId: string;
            ptyId?: string | null;
            session: components["schemas"]["Session"];
            windowId: string;
        };
        CreatedWorktree: {
            path: string;
        };
        DeleteWorkItemRequest: {
            actor?: string;
            id: string;
        };
        DetachPanePTYRequest: {
            paneId: string;
            sessionId: string;
        };
        DetachedPanePTY: {
            ptyId: string;
            session: components["schemas"]["Session"];
        };
        DetectWorktrunkRequest: {
            overridePath: string;
            repoPath: string;
        };
        ErrorResponse: {
            error: string;
        };
        HTTPForward: {
            id: string;
            name: string;
            sessionId: string;
            targetUrl: string;
        };
        HistoryEvent: {
            actor?: string;
            /** Format: date-time */
            at: string;
            attachmentId?: string;
            branch?: string;
            id: string;
            message?: string;
            stageId?: string;
            type: string;
            worktreePath?: string;
        };
        KillPTYRequest: {
            ptyId: string;
        };
        LayoutNode: {
            children?: components["schemas"]["LayoutNode"][];
            direction?: string;
            kind: string;
            paneId?: string;
            sizes?: number[];
        };
        ListWorktreesRequest: {
            repoPath: string;
        };
        MarkStatusEventReadRequest: {
            id: string;
        };
        MoveWorkItemRequest: {
            actor?: string;
            id: string;
            stageId: string;
        };
        OutputSnapshot: {
            /** Format: int64 */
            offset: number;
            output: string;
            outputBase64: string;
            ptyId: string;
        };
        PTYInfo: {
            /** Format: int64 */
            cols: number;
            /** Format: int64 */
            exitCode?: number | null;
            id: string;
            originPaneId: string;
            originWindowId: string;
            paneId: string;
            /** Format: int64 */
            rows: number;
            running: boolean;
            sessionId: string;
            status: string;
            windowId: string;
            workingDir: string;
        };
        Pane: {
            currentPtyId?: string | null;
            id: string;
            windowId: string;
            workingDir: string;
        };
        Project: {
            /** Format: date-time */
            createdAt: string;
            id: string;
            name: string;
            /** Format: int64 */
            nextWorkItemNumber: number;
            rootDir: string;
            slug: string;
            /** Format: date-time */
            updatedAt: string;
            workflow: components["schemas"]["ProjectWorkflow"];
        };
        ProjectWorkflow: {
            id: string;
            name: string;
            stages: components["schemas"]["WorkflowStage"][];
            templateId: string;
            transitionRules: components["schemas"]["TransitionRule"][];
        };
        PromptTemplate: {
            body: string;
            /** Format: date-time */
            createdAt: string;
            id: string;
            name: string;
            source: string;
            /** Format: date-time */
            updatedAt: string;
        };
        RemoveWorktreeRequest: {
            alsoBranch: boolean;
            force: boolean;
            repoPath: string;
            worktreePath: string;
        };
        ReportStatusRequest: {
            actor?: string;
            kind: string;
            message: string;
            projectId?: string;
            ptyId?: string;
            runId?: string;
            sessionId?: string;
            workItemId?: string;
        };
        ReportStatusResponse: {
            event: components["schemas"]["StatusEvent"];
            run?: components["schemas"]["WorkItemRun"] | null;
            workItem?: components["schemas"]["WorkItem"] | null;
        };
        ResizePTYRequest: {
            /** Format: int64 */
            cols: number;
            ptyId: string;
            /** Format: int64 */
            rows: number;
        };
        RestartPanePTYRequest: {
            options: components["schemas"]["StartPTYOptions"];
            paneId: string;
            sessionId: string;
        };
        RestartedPanePTY: {
            oldPtyId: string;
            ptyId: string;
            session: components["schemas"]["Session"];
        };
        RunEvent: {
            actor?: string;
            /** Format: date-time */
            at: string;
            id: string;
            message?: string;
            type: string;
        };
        RuntimeEvent: {
            /** Format: int64 */
            offset?: number;
            ptyId?: string;
            type: string;
        };
        Session: {
            id: string;
            name: string;
            panes: {
                [key: string]: components["schemas"]["Pane"];
            };
            rootDir: string;
            windows: {
                [key: string]: components["schemas"]["SessionWindow"];
            };
        };
        SessionWindow: {
            id: string;
            layout: components["schemas"]["LayoutNode"];
            name: string;
            sessionId: string;
        };
        SetPaneWorkingDirRequest: {
            paneId: string;
            sessionId: string;
            workingDir: string;
        };
        SetSessionRootDirRequest: {
            rootDir: string;
            sessionId: string;
        };
        SplitPaneRequest: {
            direction: string;
            initialPty?: components["schemas"]["StartPTYOptions"] | null;
            sessionId: string;
            targetPaneId: string;
            windowId: string;
        };
        SplitPaneResult: {
            legacyPtyId?: string;
            paneId: string;
            ptyId?: string | null;
            session: components["schemas"]["Session"];
        };
        StartPTYOptions: {
            /** Format: int64 */
            cols: number;
            command?: string;
            /** Format: int64 */
            rows: number;
        };
        StartPanePTYRequest: {
            options: components["schemas"]["StartPTYOptions"];
            paneId: string;
            sessionId: string;
        };
        StartWorkItemRunRequest: {
            actor?: string;
            agentProfileId?: string;
            launch?: boolean;
            preset?: string;
            promptTemplateId?: string;
            ptyId?: string;
            sessionId?: string;
            systemPrompt?: string;
            workItemId: string;
        };
        StartedPanePTY: {
            ptyId: string;
            session: components["schemas"]["Session"];
        };
        StatusEvent: {
            actor?: string;
            /** Format: date-time */
            createdAt: string;
            id: string;
            kind: string;
            message: string;
            projectId?: string;
            ptyId?: string;
            /** Format: date-time */
            readAt?: string | null;
            requiresAttention: boolean;
            runId?: string;
            scope: string;
            sessionId?: string;
            workItemId?: string;
        };
        TransitionRule: {
            fromStageId: string;
            requiresApproval?: boolean;
            requiresChecks?: boolean;
            requiresNoRunningRuns?: boolean;
            toStageId: string;
        };
        WorkItem: {
            attachments: components["schemas"]["Attachment"][];
            bodyMarkdown: string;
            /** Format: date-time */
            createdAt: string;
            history: components["schemas"]["HistoryEvent"][];
            id: string;
            /** Format: int64 */
            number: number;
            projectId: string;
            runState: string;
            stageId: string;
            title: string;
            /** Format: date-time */
            updatedAt: string;
            worktree?: components["schemas"]["WorktreeBinding"] | null;
        };
        WorkItemRun: {
            /** Format: date-time */
            completedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            history: components["schemas"]["RunEvent"][];
            id: string;
            preset: string;
            projectId: string;
            promptSnapshot: string;
            promptTemplateId: string;
            ptyId?: string;
            sessionId?: string;
            status: string;
            /** Format: date-time */
            updatedAt: string;
            workItemId: string;
        };
        WorkflowStage: {
            defaultPromptTemplateId?: string;
            defaultRunPreset?: string;
            id: string;
            kind: string;
            name: string;
            provisionWorktree?: boolean;
            /** Format: int64 */
            wipLimit?: number;
        };
        WorkflowTemplate: {
            /** Format: date-time */
            createdAt: string;
            id: string;
            name: string;
            source: string;
            stages: components["schemas"]["WorkflowStage"][];
            transitionRules: components["schemas"]["TransitionRule"][];
            /** Format: date-time */
            updatedAt: string;
        };
        Worktree: {
            branch: string;
            dirty: boolean;
            isCurrent: boolean;
            isMain: boolean;
            kind: string;
            locked: boolean;
            path: string;
        };
        WorktreeBinding: {
            base: string;
            branch: string;
            /** Format: date-time */
            createdAt: string;
            worktreePath: string;
        };
        WorktrunkBinary: {
            path: string;
            version: string;
        };
        WorktrunkStatus: {
            available: boolean;
            binary: components["schemas"]["WorktrunkBinary"];
            configFound: boolean;
        };
        WritePTYRequest: {
            data: string;
            ptyId: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCompatibility: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompatibilityResponse"];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    nextEvent: {
        parameters: {
            query?: {
                timeoutMs?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeEvent"];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listHTTPForwards: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPForward"][];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createHTTPForward: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateHTTPForwardRequest"];
            };
        };
        responses: {
            /** @description success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPForward"];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteHTTPForward: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                forwardID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description no content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listPromptTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptTemplate"][];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    removePTYBookmark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookmarkID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description no content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listPTYs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PTYInfo"][];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listPTYBookmarks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ptyID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bookmark"][];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    addPTYBookmark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ptyID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddPTYBookmarkRequest"];
            };
        };
        responses: {
            /** @description success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bookmark"];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    killPTY: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ptyID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KillPTYRequest"];
            };
        };
        responses: {
            /** @description success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PTYInfo"];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getPTYOutput: {
        parameters: {
            query?: {
                from?: number;
            };
            header?: never;
            path: {
                ptyID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutputSnapshot"];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    resizePTY: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ptyID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResizePTYRequest"];
            };
        };
        responses: {
            /** @description no content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    writePTY: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ptyID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WritePTYRequest"];
            };
        };
        responses: {
            /** @description no content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"][];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedSession"];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    closeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"][];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    detachPanePTY: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionID: string;
                paneID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DetachPanePTYRequest"];
            };
        };
        responses: {
            /** @description success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetachedPanePTY"];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    restartPanePTY: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionID: string;
                paneID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestartPanePTYRequest"];
            };
        };
        responses: {
            /** @description success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestartedPanePTY"];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    setPaneWorkingDir: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionID: string;
                paneID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPaneWorkingDirRequest"];
            };
        };
        responses: {
            /** @description success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    startPanePTY: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionID: string;
                paneID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartPanePTYRequest"];
            };
        };
        responses: {
            /** @description success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartedPanePTY"];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    setSessionRootDir: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetSessionRootDirRequest"];
            };
        };
        responses: {
            /** @description success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    splitPane: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SplitPaneRequest"];
            };
        };
        responses: {
            /** @description success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SplitPaneResult"];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    closePane: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionID: string;
                windowID: string;
                paneID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClosePaneRequest"];
            };
        };
        responses: {
            /** @description success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reportStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportStatusRequest"];
            };
        };
        responses: {
            /** @description success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportStatusResponse"];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listStatusEvents: {
        parameters: {
            query?: {
                projectId?: string;
                workItemId?: string;
                runId?: string;
                sessionId?: string;
                ptyId?: string;
                unreadOnly?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusEvent"][];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    markStatusEventRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                statusEventID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkStatusEventReadRequest"];
            };
        };
        responses: {
            /** @description success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusEvent"];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listWorkItemRuns: {
        parameters: {
            query?: {
                workItemId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkItemRun"][];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    startWorkItemRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartWorkItemRunRequest"];
            };
        };
        responses: {
            /** @description success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkItemRun"];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cancelWorkItemRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelWorkItemRunRequest"];
            };
        };
        responses: {
            /** @description success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkItemRun"];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listWorkItems: {
        parameters: {
            query?: {
                projectId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkItem"][];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createWorkItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkItemRequest"];
            };
        };
        responses: {
            /** @description success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkItem"];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    addWorkItemAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workItemID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddWorkItemAttachmentRequest"];
            };
        };
        responses: {
            /** @description success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkItem"];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    bindWorkItemWorktree: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workItemID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BindWorkItemWorktreeRequest"];
            };
        };
        responses: {
            /** @description success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkItem"];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteWorkItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workItemID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteWorkItemRequest"];
            };
        };
        responses: {
            /** @description success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkItem"];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    moveWorkItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workItemID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveWorkItemRequest"];
            };
        };
        responses: {
            /** @description success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkItem"];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listWorkflowTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowTemplate"][];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createWorktree: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorktreeRequest"];
            };
        };
        responses: {
            /** @description success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedWorktree"];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listWorktrees: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListWorktreesRequest"];
            };
        };
        responses: {
            /** @description success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Worktree"][];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    removeWorktree: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoveWorktreeRequest"];
            };
        };
        responses: {
            /** @description no content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    detectWorktrunk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DetectWorktrunkRequest"];
            };
        };
        responses: {
            /** @description success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorktrunkStatus"];
                };
            };
            /** @description error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
