// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export enum LayoutKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LayoutLeaf = "leaf",
    LayoutSplit = "split",
};

export class LayoutNode {
    "kind": LayoutKind;
    "paneId"?: string;
    "direction"?: SplitDirection;
    "children"?: LayoutNode[];
    "sizes"?: number[];

    /** Creates a new LayoutNode instance. */
    constructor($$source: Partial<LayoutNode> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = LayoutKind.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LayoutNode instance from a string or object.
     */
    static createFrom($$source: any = {}): LayoutNode {
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField3_0($$parsedSource["children"]);
        }
        if ("sizes" in $$parsedSource) {
            $$parsedSource["sizes"] = $$createField4_0($$parsedSource["sizes"]);
        }
        return new LayoutNode($$parsedSource as Partial<LayoutNode>);
    }
}

export class Pane {
    "id": string;
    "windowId": string;
    "currentPtyId"?: string | null;
    "workingDir": string;

    /** Creates a new Pane instance. */
    constructor($$source: Partial<Pane> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("windowId" in $$source)) {
            this["windowId"] = "";
        }
        if (!("workingDir" in $$source)) {
            this["workingDir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Pane instance from a string or object.
     */
    static createFrom($$source: any = {}): Pane {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Pane($$parsedSource as Partial<Pane>);
    }
}

export class Session {
    "id": string;
    "name": string;
    "rootDir": string;
    "windows": { [_ in string]?: SessionWindow };
    "panes": { [_ in string]?: Pane };

    /** Creates a new Session instance. */
    constructor($$source: Partial<Session> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("rootDir" in $$source)) {
            this["rootDir"] = "";
        }
        if (!("windows" in $$source)) {
            this["windows"] = {};
        }
        if (!("panes" in $$source)) {
            this["panes"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     */
    static createFrom($$source: any = {}): Session {
        const $$createField3_0 = $$createType4;
        const $$createField4_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("windows" in $$parsedSource) {
            $$parsedSource["windows"] = $$createField3_0($$parsedSource["windows"]);
        }
        if ("panes" in $$parsedSource) {
            $$parsedSource["panes"] = $$createField4_0($$parsedSource["panes"]);
        }
        return new Session($$parsedSource as Partial<Session>);
    }
}

export class SessionWindow {
    "id": string;
    "sessionId": string;
    "name": string;
    "layout": LayoutNode;

    /** Creates a new SessionWindow instance. */
    constructor($$source: Partial<SessionWindow> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("layout" in $$source)) {
            this["layout"] = (new LayoutNode());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionWindow instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionWindow {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("layout" in $$parsedSource) {
            $$parsedSource["layout"] = $$createField3_0($$parsedSource["layout"]);
        }
        return new SessionWindow($$parsedSource as Partial<SessionWindow>);
    }
}

export enum SplitDirection {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SplitHorizontal = "horizontal",
    SplitVertical = "vertical",
};

// Private type creation functions
const $$createType0 = LayoutNode.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = SessionWindow.createFrom;
const $$createType4 = $Create.Map($Create.Any, $$createType3);
const $$createType5 = Pane.createFrom;
const $$createType6 = $Create.Map($Create.Any, $$createType5);
