// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Settings {
    "startupView": string;

    /**
     * KeepDaemonAlive controls whether a daemon the app started is left running after the app
     * quits. It defaults to true so sessions persist across app restarts; setting it false makes
     * the app stop the daemon it started on quit.
     */
    "keepDaemonAlive": boolean;
    "hookLogEnabled"?: boolean | null;
    "clearHookLogAfterSession"?: boolean;

    /**
     * Keybindings holds user overrides for editable keyboard shortcuts, keyed by command id
     * (e.g. "open-preferences") with an accelerator value (e.g. "Cmd+Shift+P"). Commands absent
     * from the map use their built-in default; an empty map means all defaults.
     */
    "keybindings"?: { [_ in string]?: string };

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("startupView" in $$source)) {
            this["startupView"] = "";
        }
        if (!("keepDaemonAlive" in $$source)) {
            this["keepDaemonAlive"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("keybindings" in $$parsedSource) {
            $$parsedSource["keybindings"] = $$createField4_0($$parsedSource["keybindings"]);
        }
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
