// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * PluginRegistryConfig describes one plugin registry source.
 */
export class PluginRegistryConfig {
    /**
     * Name is the registry namespace (e.g. "phin-tech", "acme"). Plugins from
     * this registry install under it, so names must be unique.
     */
    "name": string;

    /**
     * Source locates the registry: "owner/repo[@ref]", a GitHub/SSH URL, or a
     * local directory.
     */
    "source": string;

    /**
     * Transport forces a fetch mechanism: "tarball" (GitHub HTTP, default for
     * owner/repo), "git" (shell out to git, reusing local SSH/credential auth),
     * or "local" (a directory). Empty auto-detects from Source.
     */
    "transport"?: string;

    /**
     * TokenEnv names an environment variable holding a token for private
     * tarball/API access. The secret is never persisted in settings.
     */
    "tokenEnv"?: string;

    /** Creates a new PluginRegistryConfig instance. */
    constructor($$source: Partial<PluginRegistryConfig> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginRegistryConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): PluginRegistryConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PluginRegistryConfig($$parsedSource as Partial<PluginRegistryConfig>);
    }
}

export class Settings {
    "startupView": string;

    /**
     * KeepDaemonAlive controls whether a daemon the app started is left running after the app
     * quits. It defaults to true so sessions persist across app restarts; setting it false makes
     * the app stop the daemon it started on quit.
     */
    "keepDaemonAlive": boolean;
    "autoRestartManagedDaemon"?: boolean;
    "hookLogEnabled": boolean;
    "clearHookLogAfterSession"?: boolean;
    "worktrunkPath"?: string;

    /**
     * Keybindings holds user overrides for editable keyboard shortcuts, keyed by command id
     * (e.g. "open-preferences") with an accelerator value (e.g. "Cmd+Shift+P"). Commands absent
     * from the map use their built-in default; an empty map means all defaults.
     */
    "keybindings"?: { [_ in string]?: string };
    "trustedPlugins"?: string[];

    /**
     * PluginRegistries configures the plugin registries the daemon can install
     * from. When empty, the daemon falls back to the WHISK_PLUGIN_REGISTRY env
     * var and then a built-in default. Each registry installs into its own
     * namespace, so two registries may advertise the same plugin id.
     */
    "pluginRegistries"?: PluginRegistryConfig[];

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("startupView" in $$source)) {
            this["startupView"] = "";
        }
        if (!("keepDaemonAlive" in $$source)) {
            this["keepDaemonAlive"] = false;
        }
        if (!("hookLogEnabled" in $$source)) {
            this["hookLogEnabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType1;
        const $$createField8_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("keybindings" in $$parsedSource) {
            $$parsedSource["keybindings"] = $$createField6_0($$parsedSource["keybindings"]);
        }
        if ("trustedPlugins" in $$parsedSource) {
            $$parsedSource["trustedPlugins"] = $$createField7_0($$parsedSource["trustedPlugins"]);
        }
        if ("pluginRegistries" in $$parsedSource) {
            $$parsedSource["pluginRegistries"] = $$createField8_0($$parsedSource["pluginRegistries"]);
        }
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = PluginRegistryConfig.createFrom;
const $$createType3 = $Create.Array($$createType2);
