// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CommandView is the JSON-friendly projection sent to the frontend panel, carrying the effective
 * accelerator (override if set, otherwise the default).
 */
export class CommandView {
    "id": string;
    "label": string;
    "category": string;
    "accelerator": string;
    "default": string;
    "editable": boolean;

    /** Creates a new CommandView instance. */
    constructor($$source: Partial<CommandView> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("category" in $$source)) {
            this["category"] = "";
        }
        if (!("accelerator" in $$source)) {
            this["accelerator"] = "";
        }
        if (!("default" in $$source)) {
            this["default"] = "";
        }
        if (!("editable" in $$source)) {
            this["editable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommandView instance from a string or object.
     */
    static createFrom($$source: any = {}): CommandView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommandView($$parsedSource as Partial<CommandView>);
    }
}

/**
 * KeybindingsView is the payload returned by the service for the panel: the full command registry
 * with each command's effective accelerator resolved.
 */
export class KeybindingsView {
    "commands": CommandView[];

    /** Creates a new KeybindingsView instance. */
    constructor($$source: Partial<KeybindingsView> = {}) {
        if (!("commands" in $$source)) {
            this["commands"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KeybindingsView instance from a string or object.
     */
    static createFrom($$source: any = {}): KeybindingsView {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("commands" in $$parsedSource) {
            $$parsedSource["commands"] = $$createField0_0($$parsedSource["commands"]);
        }
        return new KeybindingsView($$parsedSource as Partial<KeybindingsView>);
    }
}

/**
 * SessionRef is the minimal session description the frontend pushes to keep the Sessions menu in
 * sync. Order matches the session bar; Index 0 is the first session (Cmd+1).
 */
export class SessionRef {
    "id": string;
    "name": string;

    /** Creates a new SessionRef instance. */
    constructor($$source: Partial<SessionRef> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionRef instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionRef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionRef($$parsedSource as Partial<SessionRef>);
    }
}

// Private type creation functions
const $$createType0 = CommandView.createFrom;
const $$createType1 = $Create.Array($$createType0);
