// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as session$0 from "../domain/session/models.js";

export class CreateSessionRequest {
    "name": string;
    "workingDir": string;
    "cols": number;
    "rows": number;

    /** Creates a new CreateSessionRequest instance. */
    constructor($$source: Partial<CreateSessionRequest> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("workingDir" in $$source)) {
            this["workingDir"] = "";
        }
        if (!("cols" in $$source)) {
            this["cols"] = 0;
        }
        if (!("rows" in $$source)) {
            this["rows"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateSessionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateSessionRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateSessionRequest($$parsedSource as Partial<CreateSessionRequest>);
    }
}

export class CreateWorktreeRequest {
    "repoPath": string;
    "branch": string;
    "base": string;

    /** Creates a new CreateWorktreeRequest instance. */
    constructor($$source: Partial<CreateWorktreeRequest> = {}) {
        if (!("repoPath" in $$source)) {
            this["repoPath"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("base" in $$source)) {
            this["base"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateWorktreeRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateWorktreeRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateWorktreeRequest($$parsedSource as Partial<CreateWorktreeRequest>);
    }
}

export class CreatedSession {
    "session": session$0.Session;
    "mainPtyId": string;

    /** Creates a new CreatedSession instance. */
    constructor($$source: Partial<CreatedSession> = {}) {
        if (!("session" in $$source)) {
            this["session"] = (new session$0.Session());
        }
        if (!("mainPtyId" in $$source)) {
            this["mainPtyId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreatedSession instance from a string or object.
     */
    static createFrom($$source: any = {}): CreatedSession {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        return new CreatedSession($$parsedSource as Partial<CreatedSession>);
    }
}

export class CreatedWorktree {
    "path": string;

    /** Creates a new CreatedWorktree instance. */
    constructor($$source: Partial<CreatedWorktree> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreatedWorktree instance from a string or object.
     */
    static createFrom($$source: any = {}): CreatedWorktree {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreatedWorktree($$parsedSource as Partial<CreatedWorktree>);
    }
}

export class DetectWorktrunkRequest {
    "repoPath": string;
    "overridePath": string;

    /** Creates a new DetectWorktrunkRequest instance. */
    constructor($$source: Partial<DetectWorktrunkRequest> = {}) {
        if (!("repoPath" in $$source)) {
            this["repoPath"] = "";
        }
        if (!("overridePath" in $$source)) {
            this["overridePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DetectWorktrunkRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): DetectWorktrunkRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DetectWorktrunkRequest($$parsedSource as Partial<DetectWorktrunkRequest>);
    }
}

export class HTTPForward {
    "id": string;
    "name": string;
    "targetUrl": string;
    "sessionId": string;

    /** Creates a new HTTPForward instance. */
    constructor($$source: Partial<HTTPForward> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("targetUrl" in $$source)) {
            this["targetUrl"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HTTPForward instance from a string or object.
     */
    static createFrom($$source: any = {}): HTTPForward {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HTTPForward($$parsedSource as Partial<HTTPForward>);
    }
}

export class ListWorktreesRequest {
    "repoPath": string;

    /** Creates a new ListWorktreesRequest instance. */
    constructor($$source: Partial<ListWorktreesRequest> = {}) {
        if (!("repoPath" in $$source)) {
            this["repoPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListWorktreesRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ListWorktreesRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListWorktreesRequest($$parsedSource as Partial<ListWorktreesRequest>);
    }
}

export class OutputRequest {
    "ptyId": string;
    "fromOffset": number;

    /** Creates a new OutputRequest instance. */
    constructor($$source: Partial<OutputRequest> = {}) {
        if (!("ptyId" in $$source)) {
            this["ptyId"] = "";
        }
        if (!("fromOffset" in $$source)) {
            this["fromOffset"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OutputRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): OutputRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OutputRequest($$parsedSource as Partial<OutputRequest>);
    }
}

export class OutputSnapshot {
    "ptyId": string;
    "offset": number;
    "output": string;

    /** Creates a new OutputSnapshot instance. */
    constructor($$source: Partial<OutputSnapshot> = {}) {
        if (!("ptyId" in $$source)) {
            this["ptyId"] = "";
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("output" in $$source)) {
            this["output"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OutputSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): OutputSnapshot {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OutputSnapshot($$parsedSource as Partial<OutputSnapshot>);
    }
}

export class RemoveWorktreeRequest {
    "repoPath": string;
    "worktreePath": string;
    "alsoBranch": boolean;
    "force": boolean;

    /** Creates a new RemoveWorktreeRequest instance. */
    constructor($$source: Partial<RemoveWorktreeRequest> = {}) {
        if (!("repoPath" in $$source)) {
            this["repoPath"] = "";
        }
        if (!("worktreePath" in $$source)) {
            this["worktreePath"] = "";
        }
        if (!("alsoBranch" in $$source)) {
            this["alsoBranch"] = false;
        }
        if (!("force" in $$source)) {
            this["force"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoveWorktreeRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): RemoveWorktreeRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RemoveWorktreeRequest($$parsedSource as Partial<RemoveWorktreeRequest>);
    }
}

export class ResizePTYRequest {
    "ptyId": string;
    "cols": number;
    "rows": number;

    /** Creates a new ResizePTYRequest instance. */
    constructor($$source: Partial<ResizePTYRequest> = {}) {
        if (!("ptyId" in $$source)) {
            this["ptyId"] = "";
        }
        if (!("cols" in $$source)) {
            this["cols"] = 0;
        }
        if (!("rows" in $$source)) {
            this["rows"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResizePTYRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ResizePTYRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResizePTYRequest($$parsedSource as Partial<ResizePTYRequest>);
    }
}

export class SplitPaneRequest {
    "sessionId": string;
    "targetPaneId": string;
    "direction": string;
    "cols": number;
    "rows": number;

    /** Creates a new SplitPaneRequest instance. */
    constructor($$source: Partial<SplitPaneRequest> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("targetPaneId" in $$source)) {
            this["targetPaneId"] = "";
        }
        if (!("direction" in $$source)) {
            this["direction"] = "";
        }
        if (!("cols" in $$source)) {
            this["cols"] = 0;
        }
        if (!("rows" in $$source)) {
            this["rows"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SplitPaneRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SplitPaneRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SplitPaneRequest($$parsedSource as Partial<SplitPaneRequest>);
    }
}

export class SplitPaneResult {
    "session": session$0.Session;
    "paneId": string;
    "ptyId": string;

    /** Creates a new SplitPaneResult instance. */
    constructor($$source: Partial<SplitPaneResult> = {}) {
        if (!("session" in $$source)) {
            this["session"] = (new session$0.Session());
        }
        if (!("paneId" in $$source)) {
            this["paneId"] = "";
        }
        if (!("ptyId" in $$source)) {
            this["ptyId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SplitPaneResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SplitPaneResult {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        return new SplitPaneResult($$parsedSource as Partial<SplitPaneResult>);
    }
}

export class StartHTTPForwardRequest {
    "name": string;
    "targetUrl": string;
    "sessionId": string;

    /** Creates a new StartHTTPForwardRequest instance. */
    constructor($$source: Partial<StartHTTPForwardRequest> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("targetUrl" in $$source)) {
            this["targetUrl"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartHTTPForwardRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): StartHTTPForwardRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartHTTPForwardRequest($$parsedSource as Partial<StartHTTPForwardRequest>);
    }
}

export class StartedHTTPForward {
    "id": string;
    "localUrl": string;
    "forward": HTTPForward;

    /** Creates a new StartedHTTPForward instance. */
    constructor($$source: Partial<StartedHTTPForward> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("localUrl" in $$source)) {
            this["localUrl"] = "";
        }
        if (!("forward" in $$source)) {
            this["forward"] = (new HTTPForward());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartedHTTPForward instance from a string or object.
     */
    static createFrom($$source: any = {}): StartedHTTPForward {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("forward" in $$parsedSource) {
            $$parsedSource["forward"] = $$createField2_0($$parsedSource["forward"]);
        }
        return new StartedHTTPForward($$parsedSource as Partial<StartedHTTPForward>);
    }
}

export class Worktree {
    "branch": string;
    "path": string;
    "kind": string;
    "isMain": boolean;
    "isCurrent": boolean;
    "dirty": boolean;
    "locked": boolean;

    /** Creates a new Worktree instance. */
    constructor($$source: Partial<Worktree> = {}) {
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("isMain" in $$source)) {
            this["isMain"] = false;
        }
        if (!("isCurrent" in $$source)) {
            this["isCurrent"] = false;
        }
        if (!("dirty" in $$source)) {
            this["dirty"] = false;
        }
        if (!("locked" in $$source)) {
            this["locked"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Worktree instance from a string or object.
     */
    static createFrom($$source: any = {}): Worktree {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Worktree($$parsedSource as Partial<Worktree>);
    }
}

export class WorktrunkBinary {
    "path": string;
    "version": string;

    /** Creates a new WorktrunkBinary instance. */
    constructor($$source: Partial<WorktrunkBinary> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorktrunkBinary instance from a string or object.
     */
    static createFrom($$source: any = {}): WorktrunkBinary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorktrunkBinary($$parsedSource as Partial<WorktrunkBinary>);
    }
}

export class WorktrunkStatus {
    "available": boolean;
    "configFound": boolean;
    "binary": WorktrunkBinary;

    /** Creates a new WorktrunkStatus instance. */
    constructor($$source: Partial<WorktrunkStatus> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("configFound" in $$source)) {
            this["configFound"] = false;
        }
        if (!("binary" in $$source)) {
            this["binary"] = (new WorktrunkBinary());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorktrunkStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): WorktrunkStatus {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("binary" in $$parsedSource) {
            $$parsedSource["binary"] = $$createField2_0($$parsedSource["binary"]);
        }
        return new WorktrunkStatus($$parsedSource as Partial<WorktrunkStatus>);
    }
}

export class WritePTYRequest {
    "ptyId": string;
    "data": string;

    /** Creates a new WritePTYRequest instance. */
    constructor($$source: Partial<WritePTYRequest> = {}) {
        if (!("ptyId" in $$source)) {
            this["ptyId"] = "";
        }
        if (!("data" in $$source)) {
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WritePTYRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): WritePTYRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WritePTYRequest($$parsedSource as Partial<WritePTYRequest>);
    }
}

// Private type creation functions
const $$createType0 = session$0.Session.createFrom;
const $$createType1 = HTTPForward.createFrom;
const $$createType2 = WorktrunkBinary.createFrom;
