// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as session$0 from "../domain/session/models.js";

export class CreateSessionRequest {
    "name": string;
    "workingDir": string;
    "cols": number;
    "rows": number;

    /** Creates a new CreateSessionRequest instance. */
    constructor($$source: Partial<CreateSessionRequest> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("workingDir" in $$source)) {
            this["workingDir"] = "";
        }
        if (!("cols" in $$source)) {
            this["cols"] = 0;
        }
        if (!("rows" in $$source)) {
            this["rows"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateSessionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateSessionRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateSessionRequest($$parsedSource as Partial<CreateSessionRequest>);
    }
}

export class CreatedSession {
    "session": session$0.Session;
    "mainPtyId": string;

    /** Creates a new CreatedSession instance. */
    constructor($$source: Partial<CreatedSession> = {}) {
        if (!("session" in $$source)) {
            this["session"] = (new session$0.Session());
        }
        if (!("mainPtyId" in $$source)) {
            this["mainPtyId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreatedSession instance from a string or object.
     */
    static createFrom($$source: any = {}): CreatedSession {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        return new CreatedSession($$parsedSource as Partial<CreatedSession>);
    }
}

export class NextEventRequest {
    "timeoutMs": number;

    /** Creates a new NextEventRequest instance. */
    constructor($$source: Partial<NextEventRequest> = {}) {
        if (!("timeoutMs" in $$source)) {
            this["timeoutMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NextEventRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): NextEventRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NextEventRequest($$parsedSource as Partial<NextEventRequest>);
    }
}

export class OutputRequest {
    "ptyId": string;
    "fromOffset": number;

    /** Creates a new OutputRequest instance. */
    constructor($$source: Partial<OutputRequest> = {}) {
        if (!("ptyId" in $$source)) {
            this["ptyId"] = "";
        }
        if (!("fromOffset" in $$source)) {
            this["fromOffset"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OutputRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): OutputRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OutputRequest($$parsedSource as Partial<OutputRequest>);
    }
}

export class OutputSnapshot {
    "ptyId": string;
    "offset": number;
    "output": string;
    "outputBase64": string;

    /** Creates a new OutputSnapshot instance. */
    constructor($$source: Partial<OutputSnapshot> = {}) {
        if (!("ptyId" in $$source)) {
            this["ptyId"] = "";
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("output" in $$source)) {
            this["output"] = "";
        }
        if (!("outputBase64" in $$source)) {
            this["outputBase64"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OutputSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): OutputSnapshot {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OutputSnapshot($$parsedSource as Partial<OutputSnapshot>);
    }
}

export class PTYInfo {
    "id": string;
    "workingDir": string;
    "cols": number;
    "rows": number;
    "running": boolean;
    "sessionId": string;
    "paneId": string;

    /** Creates a new PTYInfo instance. */
    constructor($$source: Partial<PTYInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("workingDir" in $$source)) {
            this["workingDir"] = "";
        }
        if (!("cols" in $$source)) {
            this["cols"] = 0;
        }
        if (!("rows" in $$source)) {
            this["rows"] = 0;
        }
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("paneId" in $$source)) {
            this["paneId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PTYInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): PTYInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PTYInfo($$parsedSource as Partial<PTYInfo>);
    }
}

export class ResizePTYRequest {
    "ptyId": string;
    "cols": number;
    "rows": number;

    /** Creates a new ResizePTYRequest instance. */
    constructor($$source: Partial<ResizePTYRequest> = {}) {
        if (!("ptyId" in $$source)) {
            this["ptyId"] = "";
        }
        if (!("cols" in $$source)) {
            this["cols"] = 0;
        }
        if (!("rows" in $$source)) {
            this["rows"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResizePTYRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ResizePTYRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResizePTYRequest($$parsedSource as Partial<ResizePTYRequest>);
    }
}

export class RuntimeEvent {
    "type": string;
    "ptyId"?: string;
    "offset"?: number;

    /** Creates a new RuntimeEvent instance. */
    constructor($$source: Partial<RuntimeEvent> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): RuntimeEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RuntimeEvent($$parsedSource as Partial<RuntimeEvent>);
    }
}

export class SplitPaneRequest {
    "sessionId": string;
    "targetPaneId": string;
    "direction": string;
    "cols": number;
    "rows": number;

    /** Creates a new SplitPaneRequest instance. */
    constructor($$source: Partial<SplitPaneRequest> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("targetPaneId" in $$source)) {
            this["targetPaneId"] = "";
        }
        if (!("direction" in $$source)) {
            this["direction"] = "";
        }
        if (!("cols" in $$source)) {
            this["cols"] = 0;
        }
        if (!("rows" in $$source)) {
            this["rows"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SplitPaneRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SplitPaneRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SplitPaneRequest($$parsedSource as Partial<SplitPaneRequest>);
    }
}

export class SplitPaneResult {
    "session": session$0.Session;
    "paneId": string;
    "ptyId": string;

    /** Creates a new SplitPaneResult instance. */
    constructor($$source: Partial<SplitPaneResult> = {}) {
        if (!("session" in $$source)) {
            this["session"] = (new session$0.Session());
        }
        if (!("paneId" in $$source)) {
            this["paneId"] = "";
        }
        if (!("ptyId" in $$source)) {
            this["ptyId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SplitPaneResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SplitPaneResult {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        return new SplitPaneResult($$parsedSource as Partial<SplitPaneResult>);
    }
}

export class WritePTYRequest {
    "ptyId": string;
    "data": string;

    /** Creates a new WritePTYRequest instance. */
    constructor($$source: Partial<WritePTYRequest> = {}) {
        if (!("ptyId" in $$source)) {
            this["ptyId"] = "";
        }
        if (!("data" in $$source)) {
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WritePTYRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): WritePTYRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WritePTYRequest($$parsedSource as Partial<WritePTYRequest>);
    }
}

// Private type creation functions
const $$createType0 = session$0.Session.createFrom;
