// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as onboarding$0 from "../domain/onboarding/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ptybookmark$0 from "../domain/ptybookmark/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as session$0 from "../domain/session/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workitem$0 from "../domain/workitem/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

export class AddPTYBookmarkRequest {
    "ptyId": string;
    "offset": number;
    "kind": string;
    "label": string;

    /** Creates a new AddPTYBookmarkRequest instance. */
    constructor($$source: Partial<AddPTYBookmarkRequest> = {}) {
        if (!("ptyId" in $$source)) {
            this["ptyId"] = "";
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AddPTYBookmarkRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): AddPTYBookmarkRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AddPTYBookmarkRequest($$parsedSource as Partial<AddPTYBookmarkRequest>);
    }
}

export class AddProjectAttachmentRequest {
    "projectId": string;
    "kind": string;
    "scope"?: string;
    "title"?: string;
    "path"?: string;
    "url"?: string;
    "note"?: string;
    "provider"?: string;
    "target"?: string;
    "includeInContext"?: boolean;
    "meta"?: { [_ in string]?: MetadataValue };

    /** Creates a new AddProjectAttachmentRequest instance. */
    constructor($$source: Partial<AddProjectAttachmentRequest> = {}) {
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AddProjectAttachmentRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): AddProjectAttachmentRequest {
        const $$createField10_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("meta" in $$parsedSource) {
            $$parsedSource["meta"] = $$createField10_0($$parsedSource["meta"]);
        }
        return new AddProjectAttachmentRequest($$parsedSource as Partial<AddProjectAttachmentRequest>);
    }
}

export class AddWorkItemAttachmentRequest {
    "workItemId": string;
    "kind": string;
    "scope"?: string;
    "path"?: string;
    "url"?: string;
    "note"?: string;
    "actor"?: string;

    /** Creates a new AddWorkItemAttachmentRequest instance. */
    constructor($$source: Partial<AddWorkItemAttachmentRequest> = {}) {
        if (!("workItemId" in $$source)) {
            this["workItemId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AddWorkItemAttachmentRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): AddWorkItemAttachmentRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AddWorkItemAttachmentRequest($$parsedSource as Partial<AddWorkItemAttachmentRequest>);
    }
}

export class AgentBridgeApproval {
    "id": string;
    "bridgeId": string;
    "sessionId"?: string;
    "ptyId"?: string;
    "runId"?: string;
    "provider": string;
    "eventName": string;
    "toolName": string;
    "toolInput"?: { [_ in string]?: any };
    "status": string;
    "decision"?: AgentBridgeHookDecision;
    "createdAt": time$0.Time;
    "resolvedAt"?: time$0.Time | null;

    /** Creates a new AgentBridgeApproval instance. */
    constructor($$source: Partial<AgentBridgeApproval> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("bridgeId" in $$source)) {
            this["bridgeId"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("eventName" in $$source)) {
            this["eventName"] = "";
        }
        if (!("toolName" in $$source)) {
            this["toolName"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentBridgeApproval instance from a string or object.
     */
    static createFrom($$source: any = {}): AgentBridgeApproval {
        const $$createField8_0 = $$createType2;
        const $$createField10_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("toolInput" in $$parsedSource) {
            $$parsedSource["toolInput"] = $$createField8_0($$parsedSource["toolInput"]);
        }
        if ("decision" in $$parsedSource) {
            $$parsedSource["decision"] = $$createField10_0($$parsedSource["decision"]);
        }
        return new AgentBridgeApproval($$parsedSource as Partial<AgentBridgeApproval>);
    }
}

export class AgentBridgeEvent {
    "id": string;
    "bridgeId"?: string;
    "sessionId"?: string;
    "ptyId"?: string;
    "provider": string;
    "eventName": string;
    "toolName"?: string;
    "message"?: string;
    "notificationType"?: string;
    "elicitationId"?: string;
    "action"?: string;
    "result"?: string;
    "status": string;
    "createdAt": time$0.Time;
    "raw"?: { [_ in string]?: any };

    /** Creates a new AgentBridgeEvent instance. */
    constructor($$source: Partial<AgentBridgeEvent> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("eventName" in $$source)) {
            this["eventName"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentBridgeEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): AgentBridgeEvent {
        const $$createField14_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("raw" in $$parsedSource) {
            $$parsedSource["raw"] = $$createField14_0($$parsedSource["raw"]);
        }
        return new AgentBridgeEvent($$parsedSource as Partial<AgentBridgeEvent>);
    }
}

export class AgentBridgeHookDecision {
    "action"?: string;
    "reason"?: string;

    /** Creates a new AgentBridgeHookDecision instance. */
    constructor($$source: Partial<AgentBridgeHookDecision> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentBridgeHookDecision instance from a string or object.
     */
    static createFrom($$source: any = {}): AgentBridgeHookDecision {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AgentBridgeHookDecision($$parsedSource as Partial<AgentBridgeHookDecision>);
    }
}

export class AgentHookIntegration {
    "provider": string;
    "status": string;
    "installedVersion"?: string;
    "latestVersion": string;
    "helperPath": string;
    "configPath": string;
    "manifestPath": string;
    "detail"?: string;

    /** Creates a new AgentHookIntegration instance. */
    constructor($$source: Partial<AgentHookIntegration> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("latestVersion" in $$source)) {
            this["latestVersion"] = "";
        }
        if (!("helperPath" in $$source)) {
            this["helperPath"] = "";
        }
        if (!("configPath" in $$source)) {
            this["configPath"] = "";
        }
        if (!("manifestPath" in $$source)) {
            this["manifestPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentHookIntegration instance from a string or object.
     */
    static createFrom($$source: any = {}): AgentHookIntegration {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AgentHookIntegration($$parsedSource as Partial<AgentHookIntegration>);
    }
}

export class AgentHookIntegrationRequest {
    "provider": string;

    /** Creates a new AgentHookIntegrationRequest instance. */
    constructor($$source: Partial<AgentHookIntegrationRequest> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentHookIntegrationRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): AgentHookIntegrationRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AgentHookIntegrationRequest($$parsedSource as Partial<AgentHookIntegrationRequest>);
    }
}

export class AgentHookLogStatus {
    "enabled": boolean;
    "clearAfterSession": boolean;
    "path": string;
    "sizeBytes": number;

    /** Creates a new AgentHookLogStatus instance. */
    constructor($$source: Partial<AgentHookLogStatus> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("clearAfterSession" in $$source)) {
            this["clearAfterSession"] = false;
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("sizeBytes" in $$source)) {
            this["sizeBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentHookLogStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): AgentHookLogStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AgentHookLogStatus($$parsedSource as Partial<AgentHookLogStatus>);
    }
}

export class AnswerQuestionRequest {
    "id": string;
    "answer": string;
    "actor"?: string;

    /** Creates a new AnswerQuestionRequest instance. */
    constructor($$source: Partial<AnswerQuestionRequest> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("answer" in $$source)) {
            this["answer"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AnswerQuestionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): AnswerQuestionRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AnswerQuestionRequest($$parsedSource as Partial<AnswerQuestionRequest>);
    }
}

export class ApproveDoneRequest {
    "workItemId": string;
    "reason"?: string;
    "actor"?: string;

    /** Creates a new ApproveDoneRequest instance. */
    constructor($$source: Partial<ApproveDoneRequest> = {}) {
        if (!("workItemId" in $$source)) {
            this["workItemId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApproveDoneRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ApproveDoneRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ApproveDoneRequest($$parsedSource as Partial<ApproveDoneRequest>);
    }
}

export class ApprovePlanRequest {
    "artifactId": string;
    "workItemId": string;
    "actor"?: string;

    /** Creates a new ApprovePlanRequest instance. */
    constructor($$source: Partial<ApprovePlanRequest> = {}) {
        if (!("artifactId" in $$source)) {
            this["artifactId"] = "";
        }
        if (!("workItemId" in $$source)) {
            this["workItemId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApprovePlanRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ApprovePlanRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ApprovePlanRequest($$parsedSource as Partial<ApprovePlanRequest>);
    }
}

export const Artifact = workitem$0.Artifact;
export type Artifact = workitem$0.Artifact;

export class AskQuestionRequest {
    "workItemId"?: string;
    "runId"?: string;
    "sessionId"?: string;
    "ptyId"?: string;
    "prompt": string;
    "actor"?: string;

    /** Creates a new AskQuestionRequest instance. */
    constructor($$source: Partial<AskQuestionRequest> = {}) {
        if (!("prompt" in $$source)) {
            this["prompt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AskQuestionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): AskQuestionRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AskQuestionRequest($$parsedSource as Partial<AskQuestionRequest>);
    }
}

export class BindWorkItemWorktreeRequest {
    "id": string;
    "branch": string;
    "base"?: string;
    "worktreePath": string;
    "actor"?: string;

    /** Creates a new BindWorkItemWorktreeRequest instance. */
    constructor($$source: Partial<BindWorkItemWorktreeRequest> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("worktreePath" in $$source)) {
            this["worktreePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BindWorkItemWorktreeRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): BindWorkItemWorktreeRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BindWorkItemWorktreeRequest($$parsedSource as Partial<BindWorkItemWorktreeRequest>);
    }
}

export class CancelWorkItemRunRequest {
    "id": string;
    "actor"?: string;

    /** Creates a new CancelWorkItemRunRequest instance. */
    constructor($$source: Partial<CancelWorkItemRunRequest> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CancelWorkItemRunRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CancelWorkItemRunRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CancelWorkItemRunRequest($$parsedSource as Partial<CancelWorkItemRunRequest>);
    }
}

export class ClearDaemonRequest {

    /** Creates a new ClearDaemonRequest instance. */
    constructor($$source: Partial<ClearDaemonRequest> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClearDaemonRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ClearDaemonRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClearDaemonRequest($$parsedSource as Partial<ClearDaemonRequest>);
    }
}

export class ClearDaemonResponse {
    "sessionsCleared": number;
    "ptysCleared": number;
    "bookmarksCleared": number;
    "projectsCleared": number;
    "workItemsCleared": number;
    "forwardsCleared": number;

    /** Creates a new ClearDaemonResponse instance. */
    constructor($$source: Partial<ClearDaemonResponse> = {}) {
        if (!("sessionsCleared" in $$source)) {
            this["sessionsCleared"] = 0;
        }
        if (!("ptysCleared" in $$source)) {
            this["ptysCleared"] = 0;
        }
        if (!("bookmarksCleared" in $$source)) {
            this["bookmarksCleared"] = 0;
        }
        if (!("projectsCleared" in $$source)) {
            this["projectsCleared"] = 0;
        }
        if (!("workItemsCleared" in $$source)) {
            this["workItemsCleared"] = 0;
        }
        if (!("forwardsCleared" in $$source)) {
            this["forwardsCleared"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClearDaemonResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ClearDaemonResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClearDaemonResponse($$parsedSource as Partial<ClearDaemonResponse>);
    }
}

export class ClosePaneRequest {
    "sessionId": string;
    "windowId": string;
    "paneId": string;

    /** Creates a new ClosePaneRequest instance. */
    constructor($$source: Partial<ClosePaneRequest> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("windowId" in $$source)) {
            this["windowId"] = "";
        }
        if (!("paneId" in $$source)) {
            this["paneId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClosePaneRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ClosePaneRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClosePaneRequest($$parsedSource as Partial<ClosePaneRequest>);
    }
}

export class CloseSessionRequest {
    "sessionId": string;

    /** Creates a new CloseSessionRequest instance. */
    constructor($$source: Partial<CloseSessionRequest> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CloseSessionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CloseSessionRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CloseSessionRequest($$parsedSource as Partial<CloseSessionRequest>);
    }
}

export class CompleteExecutionRequest {
    "workItemId"?: string;
    "runId": string;
    "message"?: string;
    "actor"?: string;

    /** Creates a new CompleteExecutionRequest instance. */
    constructor($$source: Partial<CompleteExecutionRequest> = {}) {
        if (!("runId" in $$source)) {
            this["runId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompleteExecutionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CompleteExecutionRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CompleteExecutionRequest($$parsedSource as Partial<CompleteExecutionRequest>);
    }
}

export class CompleteGateRequest {
    "id": string;
    "status": string;
    "overrideReason"?: string;
    "actor"?: string;

    /** Creates a new CompleteGateRequest instance. */
    constructor($$source: Partial<CompleteGateRequest> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompleteGateRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CompleteGateRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CompleteGateRequest($$parsedSource as Partial<CompleteGateRequest>);
    }
}

export class CreateProjectRequest {
    "name": string;
    "description"?: string;
    "slug"?: string;
    "rootDir": string;
    "workflowId"?: string;
    "preferences"?: ProjectPreferences;

    /** Creates a new CreateProjectRequest instance. */
    constructor($$source: Partial<CreateProjectRequest> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("rootDir" in $$source)) {
            this["rootDir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateProjectRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateProjectRequest {
        const $$createField5_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("preferences" in $$parsedSource) {
            $$parsedSource["preferences"] = $$createField5_0($$parsedSource["preferences"]);
        }
        return new CreateProjectRequest($$parsedSource as Partial<CreateProjectRequest>);
    }
}

export class CreateSessionRequest {
    "name": string;
    "rootDir": string;
    "workingDir"?: string;
    "projectId"?: string;
    "initialPty"?: StartPTYOptions | null;

    /** Creates a new CreateSessionRequest instance. */
    constructor($$source: Partial<CreateSessionRequest> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("rootDir" in $$source)) {
            this["rootDir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateSessionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateSessionRequest {
        const $$createField4_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("initialPty" in $$parsedSource) {
            $$parsedSource["initialPty"] = $$createField4_0($$parsedSource["initialPty"]);
        }
        return new CreateSessionRequest($$parsedSource as Partial<CreateSessionRequest>);
    }
}

export class CreateWorkItemRequest {
    "projectId": string;
    "workflowId"?: string;
    "title": string;
    "bodyMarkdown"?: string;
    "stageId"?: string;
    "actor"?: string;

    /** Creates a new CreateWorkItemRequest instance. */
    constructor($$source: Partial<CreateWorkItemRequest> = {}) {
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateWorkItemRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateWorkItemRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateWorkItemRequest($$parsedSource as Partial<CreateWorkItemRequest>);
    }
}

export class CreateWorktreeRequest {
    "repoPath": string;
    "branch": string;
    "base": string;

    /** Creates a new CreateWorktreeRequest instance. */
    constructor($$source: Partial<CreateWorktreeRequest> = {}) {
        if (!("repoPath" in $$source)) {
            this["repoPath"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("base" in $$source)) {
            this["base"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateWorktreeRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateWorktreeRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateWorktreeRequest($$parsedSource as Partial<CreateWorktreeRequest>);
    }
}

export class CreatedSession {
    "session": session$0.Session;
    "windowId": string;
    "paneId": string;
    "ptyId"?: string | null;
    "mainPtyId"?: string;

    /** Creates a new CreatedSession instance. */
    constructor($$source: Partial<CreatedSession> = {}) {
        if (!("session" in $$source)) {
            this["session"] = (new session$0.Session());
        }
        if (!("windowId" in $$source)) {
            this["windowId"] = "";
        }
        if (!("paneId" in $$source)) {
            this["paneId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreatedSession instance from a string or object.
     */
    static createFrom($$source: any = {}): CreatedSession {
        const $$createField0_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        return new CreatedSession($$parsedSource as Partial<CreatedSession>);
    }
}

export class CreatedWorktree {
    "path": string;

    /** Creates a new CreatedWorktree instance. */
    constructor($$source: Partial<CreatedWorktree> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreatedWorktree instance from a string or object.
     */
    static createFrom($$source: any = {}): CreatedWorktree {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreatedWorktree($$parsedSource as Partial<CreatedWorktree>);
    }
}

export class DeletePTYRequest {
    "ptyId": string;

    /** Creates a new DeletePTYRequest instance. */
    constructor($$source: Partial<DeletePTYRequest> = {}) {
        if (!("ptyId" in $$source)) {
            this["ptyId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeletePTYRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): DeletePTYRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeletePTYRequest($$parsedSource as Partial<DeletePTYRequest>);
    }
}

export class DeleteProjectAttachmentRequest {
    "projectId": string;

    /** Creates a new DeleteProjectAttachmentRequest instance. */
    constructor($$source: Partial<DeleteProjectAttachmentRequest> = {}) {
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeleteProjectAttachmentRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): DeleteProjectAttachmentRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeleteProjectAttachmentRequest($$parsedSource as Partial<DeleteProjectAttachmentRequest>);
    }
}

export class DeleteWorkItemRequest {
    "id": string;
    "actor"?: string;

    /** Creates a new DeleteWorkItemRequest instance. */
    constructor($$source: Partial<DeleteWorkItemRequest> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeleteWorkItemRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): DeleteWorkItemRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeleteWorkItemRequest($$parsedSource as Partial<DeleteWorkItemRequest>);
    }
}

export class DetachPanePTYRequest {
    "sessionId": string;
    "paneId": string;

    /** Creates a new DetachPanePTYRequest instance. */
    constructor($$source: Partial<DetachPanePTYRequest> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("paneId" in $$source)) {
            this["paneId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DetachPanePTYRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): DetachPanePTYRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DetachPanePTYRequest($$parsedSource as Partial<DetachPanePTYRequest>);
    }
}

export class DetachedPanePTY {
    "session": session$0.Session;
    "ptyId": string;

    /** Creates a new DetachedPanePTY instance. */
    constructor($$source: Partial<DetachedPanePTY> = {}) {
        if (!("session" in $$source)) {
            this["session"] = (new session$0.Session());
        }
        if (!("ptyId" in $$source)) {
            this["ptyId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DetachedPanePTY instance from a string or object.
     */
    static createFrom($$source: any = {}): DetachedPanePTY {
        const $$createField0_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        return new DetachedPanePTY($$parsedSource as Partial<DetachedPanePTY>);
    }
}

export class DetectWorktrunkRequest {
    "repoPath": string;
    "overridePath": string;

    /** Creates a new DetectWorktrunkRequest instance. */
    constructor($$source: Partial<DetectWorktrunkRequest> = {}) {
        if (!("repoPath" in $$source)) {
            this["repoPath"] = "";
        }
        if (!("overridePath" in $$source)) {
            this["overridePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DetectWorktrunkRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): DetectWorktrunkRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DetectWorktrunkRequest($$parsedSource as Partial<DetectWorktrunkRequest>);
    }
}

export const GateReport = workitem$0.GateReport;
export type GateReport = workitem$0.GateReport;

export class HTTPForward {
    "id": string;
    "name": string;
    "targetUrl": string;
    "sessionId": string;

    /** Creates a new HTTPForward instance. */
    constructor($$source: Partial<HTTPForward> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("targetUrl" in $$source)) {
            this["targetUrl"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HTTPForward instance from a string or object.
     */
    static createFrom($$source: any = {}): HTTPForward {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HTTPForward($$parsedSource as Partial<HTTPForward>);
    }
}

export class KillPTYRequest {
    "ptyId": string;

    /** Creates a new KillPTYRequest instance. */
    constructor($$source: Partial<KillPTYRequest> = {}) {
        if (!("ptyId" in $$source)) {
            this["ptyId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KillPTYRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): KillPTYRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KillPTYRequest($$parsedSource as Partial<KillPTYRequest>);
    }
}

export class LaunchExecutionRequest {
    "workItemId": string;
    "agentProfileId"?: string;
    "systemPrompt"?: string;
    "actor"?: string;

    /** Creates a new LaunchExecutionRequest instance. */
    constructor($$source: Partial<LaunchExecutionRequest> = {}) {
        if (!("workItemId" in $$source)) {
            this["workItemId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LaunchExecutionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): LaunchExecutionRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LaunchExecutionRequest($$parsedSource as Partial<LaunchExecutionRequest>);
    }
}

export class LaunchWorkItemRunRequest {
    "id": string;
    "agentProfileId"?: string;
    "systemPrompt"?: string;
    "actor"?: string;

    /** Creates a new LaunchWorkItemRunRequest instance. */
    constructor($$source: Partial<LaunchWorkItemRunRequest> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LaunchWorkItemRunRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): LaunchWorkItemRunRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LaunchWorkItemRunRequest($$parsedSource as Partial<LaunchWorkItemRunRequest>);
    }
}

export class ListAgentBridgeApprovalsRequest {
    "status"?: string;

    /** Creates a new ListAgentBridgeApprovalsRequest instance. */
    constructor($$source: Partial<ListAgentBridgeApprovalsRequest> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListAgentBridgeApprovalsRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ListAgentBridgeApprovalsRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListAgentBridgeApprovalsRequest($$parsedSource as Partial<ListAgentBridgeApprovalsRequest>);
    }
}

export class ListAgentBridgeEventsRequest {
    "status"?: string;

    /** Creates a new ListAgentBridgeEventsRequest instance. */
    constructor($$source: Partial<ListAgentBridgeEventsRequest> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListAgentBridgeEventsRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ListAgentBridgeEventsRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListAgentBridgeEventsRequest($$parsedSource as Partial<ListAgentBridgeEventsRequest>);
    }
}

export class ListStatusEventsRequest {
    "projectId"?: string;
    "workItemId"?: string;
    "runId"?: string;
    "sessionId"?: string;
    "ptyId"?: string;
    "unreadOnly"?: boolean;

    /** Creates a new ListStatusEventsRequest instance. */
    constructor($$source: Partial<ListStatusEventsRequest> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListStatusEventsRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ListStatusEventsRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListStatusEventsRequest($$parsedSource as Partial<ListStatusEventsRequest>);
    }
}

export class ListWorktreesRequest {
    "repoPath": string;

    /** Creates a new ListWorktreesRequest instance. */
    constructor($$source: Partial<ListWorktreesRequest> = {}) {
        if (!("repoPath" in $$source)) {
            this["repoPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListWorktreesRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ListWorktreesRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListWorktreesRequest($$parsedSource as Partial<ListWorktreesRequest>);
    }
}

export class MarkAgentBridgeEventReadRequest {
    "id": string;

    /** Creates a new MarkAgentBridgeEventReadRequest instance. */
    constructor($$source: Partial<MarkAgentBridgeEventReadRequest> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MarkAgentBridgeEventReadRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): MarkAgentBridgeEventReadRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MarkAgentBridgeEventReadRequest($$parsedSource as Partial<MarkAgentBridgeEventReadRequest>);
    }
}

export class MarkStatusEventReadRequest {
    "id": string;

    /** Creates a new MarkStatusEventReadRequest instance. */
    constructor($$source: Partial<MarkStatusEventReadRequest> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MarkStatusEventReadRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): MarkStatusEventReadRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MarkStatusEventReadRequest($$parsedSource as Partial<MarkStatusEventReadRequest>);
    }
}

export const MetadataValue = workitem$0.MetadataValue;
export type MetadataValue = workitem$0.MetadataValue;

export class MoveWorkItemRequest {
    "id": string;
    "stageId": string;
    "actor"?: string;

    /** Creates a new MoveWorkItemRequest instance. */
    constructor($$source: Partial<MoveWorkItemRequest> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("stageId" in $$source)) {
            this["stageId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MoveWorkItemRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): MoveWorkItemRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MoveWorkItemRequest($$parsedSource as Partial<MoveWorkItemRequest>);
    }
}

export class NextEventRequest {
    "timeoutMs": number;

    /** Creates a new NextEventRequest instance. */
    constructor($$source: Partial<NextEventRequest> = {}) {
        if (!("timeoutMs" in $$source)) {
            this["timeoutMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NextEventRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): NextEventRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NextEventRequest($$parsedSource as Partial<NextEventRequest>);
    }
}

export class OnboardingApplyRequest {
    "itemIds": string[];

    /** Creates a new OnboardingApplyRequest instance. */
    constructor($$source: Partial<OnboardingApplyRequest> = {}) {
        if (!("itemIds" in $$source)) {
            this["itemIds"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OnboardingApplyRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): OnboardingApplyRequest {
        const $$createField0_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("itemIds" in $$parsedSource) {
            $$parsedSource["itemIds"] = $$createField0_0($$parsedSource["itemIds"]);
        }
        return new OnboardingApplyRequest($$parsedSource as Partial<OnboardingApplyRequest>);
    }
}

export const OnboardingItem = onboarding$0.Item;
export type OnboardingItem = onboarding$0.Item;

export class OnboardingStatus {
    "items": OnboardingItem[];
    "shouldShow": boolean;
    "localDaemon": boolean;
    "statePath": string;

    /** Creates a new OnboardingStatus instance. */
    constructor($$source: Partial<OnboardingStatus> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("shouldShow" in $$source)) {
            this["shouldShow"] = false;
        }
        if (!("localDaemon" in $$source)) {
            this["localDaemon"] = false;
        }
        if (!("statePath" in $$source)) {
            this["statePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OnboardingStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): OnboardingStatus {
        const $$createField0_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new OnboardingStatus($$parsedSource as Partial<OnboardingStatus>);
    }
}

export class OutputRequest {
    "ptyId": string;
    "fromOffset": number;

    /** Creates a new OutputRequest instance. */
    constructor($$source: Partial<OutputRequest> = {}) {
        if (!("ptyId" in $$source)) {
            this["ptyId"] = "";
        }
        if (!("fromOffset" in $$source)) {
            this["fromOffset"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OutputRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): OutputRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OutputRequest($$parsedSource as Partial<OutputRequest>);
    }
}

export class OutputSnapshot {
    "ptyId": string;
    "offset": number;
    "output": string;
    "outputBase64": string;

    /** Creates a new OutputSnapshot instance. */
    constructor($$source: Partial<OutputSnapshot> = {}) {
        if (!("ptyId" in $$source)) {
            this["ptyId"] = "";
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("output" in $$source)) {
            this["output"] = "";
        }
        if (!("outputBase64" in $$source)) {
            this["outputBase64"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OutputSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): OutputSnapshot {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OutputSnapshot($$parsedSource as Partial<OutputSnapshot>);
    }
}

export const PTYBookmark = ptybookmark$0.Bookmark;
export type PTYBookmark = ptybookmark$0.Bookmark;

export class PTYHistory {
    "ptyId": string;
    "sessionId": string;
    "windowId": string;
    "paneId": string;
    "workingDir": string;
    "createdAt": time$0.Time;
    "exitCode"?: number | null;
    "output": string;

    /** Creates a new PTYHistory instance. */
    constructor($$source: Partial<PTYHistory> = {}) {
        if (!("ptyId" in $$source)) {
            this["ptyId"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("windowId" in $$source)) {
            this["windowId"] = "";
        }
        if (!("paneId" in $$source)) {
            this["paneId"] = "";
        }
        if (!("workingDir" in $$source)) {
            this["workingDir"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("output" in $$source)) {
            this["output"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PTYHistory instance from a string or object.
     */
    static createFrom($$source: any = {}): PTYHistory {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PTYHistory($$parsedSource as Partial<PTYHistory>);
    }
}

export class PTYHistorySummary {
    "ptyId": string;
    "sessionId": string;
    "windowId": string;
    "paneId": string;
    "workingDir": string;
    "createdAt": time$0.Time;
    "exitCode"?: number | null;

    /** Creates a new PTYHistorySummary instance. */
    constructor($$source: Partial<PTYHistorySummary> = {}) {
        if (!("ptyId" in $$source)) {
            this["ptyId"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("windowId" in $$source)) {
            this["windowId"] = "";
        }
        if (!("paneId" in $$source)) {
            this["paneId"] = "";
        }
        if (!("workingDir" in $$source)) {
            this["workingDir"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PTYHistorySummary instance from a string or object.
     */
    static createFrom($$source: any = {}): PTYHistorySummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PTYHistorySummary($$parsedSource as Partial<PTYHistorySummary>);
    }
}

export class PTYInfo {
    "id": string;
    "workingDir": string;
    "cols": number;
    "rows": number;
    "running": boolean;
    "status": string;
    "exitCode"?: number | null;
    "sessionId": string;
    "windowId": string;
    "paneId": string;
    "originWindowId": string;
    "originPaneId": string;

    /** Creates a new PTYInfo instance. */
    constructor($$source: Partial<PTYInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("workingDir" in $$source)) {
            this["workingDir"] = "";
        }
        if (!("cols" in $$source)) {
            this["cols"] = 0;
        }
        if (!("rows" in $$source)) {
            this["rows"] = 0;
        }
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("windowId" in $$source)) {
            this["windowId"] = "";
        }
        if (!("paneId" in $$source)) {
            this["paneId"] = "";
        }
        if (!("originWindowId" in $$source)) {
            this["originWindowId"] = "";
        }
        if (!("originPaneId" in $$source)) {
            this["originPaneId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PTYInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): PTYInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PTYInfo($$parsedSource as Partial<PTYInfo>);
    }
}

export class PluginResolver {
    "provider": string;
    "kinds"?: string[];

    /** Creates a new PluginResolver instance. */
    constructor($$source: Partial<PluginResolver> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginResolver instance from a string or object.
     */
    static createFrom($$source: any = {}): PluginResolver {
        const $$createField1_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("kinds" in $$parsedSource) {
            $$parsedSource["kinds"] = $$createField1_0($$parsedSource["kinds"]);
        }
        return new PluginResolver($$parsedSource as Partial<PluginResolver>);
    }
}

export class PluginStatus {
    "id": string;
    "registry"?: string;
    "name": string;
    "version": string;
    "dir": string;
    "manifestPath": string;
    "trusted": boolean;
    "valid": boolean;
    "error"?: string;
    "resolvers"?: PluginResolver[];
    "projectAttachmentTemplates"?: ProjectAttachmentTemplate[];

    /** Creates a new PluginStatus instance. */
    constructor($$source: Partial<PluginStatus> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("dir" in $$source)) {
            this["dir"] = "";
        }
        if (!("manifestPath" in $$source)) {
            this["manifestPath"] = "";
        }
        if (!("trusted" in $$source)) {
            this["trusted"] = false;
        }
        if (!("valid" in $$source)) {
            this["valid"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): PluginStatus {
        const $$createField9_0 = $$createType12;
        const $$createField10_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("resolvers" in $$parsedSource) {
            $$parsedSource["resolvers"] = $$createField9_0($$parsedSource["resolvers"]);
        }
        if ("projectAttachmentTemplates" in $$parsedSource) {
            $$parsedSource["projectAttachmentTemplates"] = $$createField10_0($$parsedSource["projectAttachmentTemplates"]);
        }
        return new PluginStatus($$parsedSource as Partial<PluginStatus>);
    }
}

export class PluginTemplateField {
    "id": string;
    "label": string;
    "type": string;
    "placeholder"?: string;
    "required"?: boolean;
    "options"?: string[];

    /** Creates a new PluginTemplateField instance. */
    constructor($$source: Partial<PluginTemplateField> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginTemplateField instance from a string or object.
     */
    static createFrom($$source: any = {}): PluginTemplateField {
        const $$createField5_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField5_0($$parsedSource["options"]);
        }
        return new PluginTemplateField($$parsedSource as Partial<PluginTemplateField>);
    }
}

export const Project = workitem$0.Project;
export type Project = workitem$0.Project;

export class ProjectAttachmentTemplate {
    "id": string;
    "label": string;
    "provider": string;
    "kind": string;
    "fields"?: PluginTemplateField[];

    /** Creates a new ProjectAttachmentTemplate instance. */
    constructor($$source: Partial<ProjectAttachmentTemplate> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectAttachmentTemplate instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectAttachmentTemplate {
        const $$createField4_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField4_0($$parsedSource["fields"]);
        }
        return new ProjectAttachmentTemplate($$parsedSource as Partial<ProjectAttachmentTemplate>);
    }
}

export class ProjectContext {
    "projectId": string;
    "items": ProjectContextItem[];

    /** Creates a new ProjectContext instance. */
    constructor($$source: Partial<ProjectContext> = {}) {
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("items" in $$source)) {
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectContext instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectContext {
        const $$createField1_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField1_0($$parsedSource["items"]);
        }
        return new ProjectContext($$parsedSource as Partial<ProjectContext>);
    }
}

export class ProjectContextItem {
    "attachmentId": string;
    "kind": string;
    "provider"?: string;
    "target"?: string;
    "title"?: string;
    "delivery": string;
    "contentType"?: string;
    "content"?: string;
    "sourceUrl"?: string;
    "error"?: string;

    /** Creates a new ProjectContextItem instance. */
    constructor($$source: Partial<ProjectContextItem> = {}) {
        if (!("attachmentId" in $$source)) {
            this["attachmentId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("delivery" in $$source)) {
            this["delivery"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectContextItem instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectContextItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectContextItem($$parsedSource as Partial<ProjectContextItem>);
    }
}

export class ProjectDetail {
    "project": Project;
    "workItems": WorkItem[];
    "sessions": session$0.Session[];
    "runs": WorkItemRun[];

    /** Creates a new ProjectDetail instance. */
    constructor($$source: Partial<ProjectDetail> = {}) {
        if (!("project" in $$source)) {
            this["project"] = (new Project());
        }
        if (!("workItems" in $$source)) {
            this["workItems"] = [];
        }
        if (!("sessions" in $$source)) {
            this["sessions"] = [];
        }
        if (!("runs" in $$source)) {
            this["runs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectDetail {
        const $$createField0_0 = $$createType19;
        const $$createField1_0 = $$createType21;
        const $$createField2_0 = $$createType22;
        const $$createField3_0 = $$createType24;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("project" in $$parsedSource) {
            $$parsedSource["project"] = $$createField0_0($$parsedSource["project"]);
        }
        if ("workItems" in $$parsedSource) {
            $$parsedSource["workItems"] = $$createField1_0($$parsedSource["workItems"]);
        }
        if ("sessions" in $$parsedSource) {
            $$parsedSource["sessions"] = $$createField2_0($$parsedSource["sessions"]);
        }
        if ("runs" in $$parsedSource) {
            $$parsedSource["runs"] = $$createField3_0($$parsedSource["runs"]);
        }
        return new ProjectDetail($$parsedSource as Partial<ProjectDetail>);
    }
}

export const ProjectPreferences = workitem$0.ProjectPreferences;
export type ProjectPreferences = workitem$0.ProjectPreferences;

export const PromptTemplate = workitem$0.PromptTemplate;
export type PromptTemplate = workitem$0.PromptTemplate;

export const Question = workitem$0.Question;
export type Question = workitem$0.Question;

export class QueueExecutionRequest {
    "workItemId": string;
    "actor"?: string;

    /** Creates a new QueueExecutionRequest instance. */
    constructor($$source: Partial<QueueExecutionRequest> = {}) {
        if (!("workItemId" in $$source)) {
            this["workItemId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueueExecutionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): QueueExecutionRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QueueExecutionRequest($$parsedSource as Partial<QueueExecutionRequest>);
    }
}

/**
 * RegistryPlugin is one installable plugin advertised by a configured plugin
 * registry, annotated with local install and trust state.
 */
export class RegistryPlugin {
    "registry": string;
    "id": string;
    "name"?: string;
    "description"?: string;
    "sourceType": string;
    "installed": boolean;
    "trusted": boolean;

    /** Creates a new RegistryPlugin instance. */
    constructor($$source: Partial<RegistryPlugin> = {}) {
        if (!("registry" in $$source)) {
            this["registry"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("sourceType" in $$source)) {
            this["sourceType"] = "";
        }
        if (!("installed" in $$source)) {
            this["installed"] = false;
        }
        if (!("trusted" in $$source)) {
            this["trusted"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RegistryPlugin instance from a string or object.
     */
    static createFrom($$source: any = {}): RegistryPlugin {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RegistryPlugin($$parsedSource as Partial<RegistryPlugin>);
    }
}

export class RemovePTYBookmarkRequest {
    "bookmarkId": string;

    /** Creates a new RemovePTYBookmarkRequest instance. */
    constructor($$source: Partial<RemovePTYBookmarkRequest> = {}) {
        if (!("bookmarkId" in $$source)) {
            this["bookmarkId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemovePTYBookmarkRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): RemovePTYBookmarkRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RemovePTYBookmarkRequest($$parsedSource as Partial<RemovePTYBookmarkRequest>);
    }
}

export class RemoveWorktreeRequest {
    "repoPath": string;
    "worktreePath": string;
    "alsoBranch": boolean;
    "force": boolean;

    /** Creates a new RemoveWorktreeRequest instance. */
    constructor($$source: Partial<RemoveWorktreeRequest> = {}) {
        if (!("repoPath" in $$source)) {
            this["repoPath"] = "";
        }
        if (!("worktreePath" in $$source)) {
            this["worktreePath"] = "";
        }
        if (!("alsoBranch" in $$source)) {
            this["alsoBranch"] = false;
        }
        if (!("force" in $$source)) {
            this["force"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoveWorktreeRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): RemoveWorktreeRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RemoveWorktreeRequest($$parsedSource as Partial<RemoveWorktreeRequest>);
    }
}

export class ReportStatusRequest {
    "kind": string;
    "message": string;
    "actor"?: string;
    "projectId"?: string;
    "workItemId"?: string;
    "runId"?: string;
    "sessionId"?: string;
    "ptyId"?: string;

    /** Creates a new ReportStatusRequest instance. */
    constructor($$source: Partial<ReportStatusRequest> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReportStatusRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ReportStatusRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReportStatusRequest($$parsedSource as Partial<ReportStatusRequest>);
    }
}

export class ReportStatusResponse {
    "event": StatusEvent;
    "run"?: WorkItemRun | null;
    "workItem"?: WorkItem | null;

    /** Creates a new ReportStatusResponse instance. */
    constructor($$source: Partial<ReportStatusResponse> = {}) {
        if (!("event" in $$source)) {
            this["event"] = (new StatusEvent());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReportStatusResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ReportStatusResponse {
        const $$createField0_0 = $$createType25;
        const $$createField1_0 = $$createType26;
        const $$createField2_0 = $$createType27;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("event" in $$parsedSource) {
            $$parsedSource["event"] = $$createField0_0($$parsedSource["event"]);
        }
        if ("run" in $$parsedSource) {
            $$parsedSource["run"] = $$createField1_0($$parsedSource["run"]);
        }
        if ("workItem" in $$parsedSource) {
            $$parsedSource["workItem"] = $$createField2_0($$parsedSource["workItem"]);
        }
        return new ReportStatusResponse($$parsedSource as Partial<ReportStatusResponse>);
    }
}

export class ResizePTYRequest {
    "ptyId": string;
    "cols": number;
    "rows": number;

    /** Creates a new ResizePTYRequest instance. */
    constructor($$source: Partial<ResizePTYRequest> = {}) {
        if (!("ptyId" in $$source)) {
            this["ptyId"] = "";
        }
        if (!("cols" in $$source)) {
            this["cols"] = 0;
        }
        if (!("rows" in $$source)) {
            this["rows"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResizePTYRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ResizePTYRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResizePTYRequest($$parsedSource as Partial<ResizePTYRequest>);
    }
}

export class ResolveAgentBridgeApprovalRequest {
    "action": string;
    "reason"?: string;

    /** Creates a new ResolveAgentBridgeApprovalRequest instance. */
    constructor($$source: Partial<ResolveAgentBridgeApprovalRequest> = {}) {
        if (!("action" in $$source)) {
            this["action"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResolveAgentBridgeApprovalRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ResolveAgentBridgeApprovalRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResolveAgentBridgeApprovalRequest($$parsedSource as Partial<ResolveAgentBridgeApprovalRequest>);
    }
}

export class RestartPanePTYRequest {
    "sessionId": string;
    "paneId": string;
    "options": StartPTYOptions;

    /** Creates a new RestartPanePTYRequest instance. */
    constructor($$source: Partial<RestartPanePTYRequest> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("paneId" in $$source)) {
            this["paneId"] = "";
        }
        if (!("options" in $$source)) {
            this["options"] = (new StartPTYOptions());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RestartPanePTYRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): RestartPanePTYRequest {
        const $$createField2_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField2_0($$parsedSource["options"]);
        }
        return new RestartPanePTYRequest($$parsedSource as Partial<RestartPanePTYRequest>);
    }
}

export class RestartedPanePTY {
    "session": session$0.Session;
    "ptyId": string;
    "oldPtyId": string;

    /** Creates a new RestartedPanePTY instance. */
    constructor($$source: Partial<RestartedPanePTY> = {}) {
        if (!("session" in $$source)) {
            this["session"] = (new session$0.Session());
        }
        if (!("ptyId" in $$source)) {
            this["ptyId"] = "";
        }
        if (!("oldPtyId" in $$source)) {
            this["oldPtyId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RestartedPanePTY instance from a string or object.
     */
    static createFrom($$source: any = {}): RestartedPanePTY {
        const $$createField0_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        return new RestartedPanePTY($$parsedSource as Partial<RestartedPanePTY>);
    }
}

export class RunPluginProjectAttachmentTemplateRequest {
    "projectId": string;
    "values"?: { [_ in string]?: string };

    /** Creates a new RunPluginProjectAttachmentTemplateRequest instance. */
    constructor($$source: Partial<RunPluginProjectAttachmentTemplateRequest> = {}) {
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunPluginProjectAttachmentTemplateRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): RunPluginProjectAttachmentTemplateRequest {
        const $$createField1_0 = $$createType28;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("values" in $$parsedSource) {
            $$parsedSource["values"] = $$createField1_0($$parsedSource["values"]);
        }
        return new RunPluginProjectAttachmentTemplateRequest($$parsedSource as Partial<RunPluginProjectAttachmentTemplateRequest>);
    }
}

export class RuntimeEvent {
    "type": string;
    "ptyId"?: string;
    "offset"?: number;

    /** Creates a new RuntimeEvent instance. */
    constructor($$source: Partial<RuntimeEvent> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): RuntimeEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RuntimeEvent($$parsedSource as Partial<RuntimeEvent>);
    }
}

export class SetAgentHookLogSettingsRequest {
    "enabled"?: boolean | null;
    "clearAfterSession"?: boolean | null;

    /** Creates a new SetAgentHookLogSettingsRequest instance. */
    constructor($$source: Partial<SetAgentHookLogSettingsRequest> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SetAgentHookLogSettingsRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SetAgentHookLogSettingsRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SetAgentHookLogSettingsRequest($$parsedSource as Partial<SetAgentHookLogSettingsRequest>);
    }
}

export class SetPaneWorkingDirRequest {
    "sessionId": string;
    "paneId": string;
    "workingDir": string;

    /** Creates a new SetPaneWorkingDirRequest instance. */
    constructor($$source: Partial<SetPaneWorkingDirRequest> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("paneId" in $$source)) {
            this["paneId"] = "";
        }
        if (!("workingDir" in $$source)) {
            this["workingDir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SetPaneWorkingDirRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SetPaneWorkingDirRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SetPaneWorkingDirRequest($$parsedSource as Partial<SetPaneWorkingDirRequest>);
    }
}

export class SetSessionProjectRequest {
    "sessionId": string;
    "projectId"?: string;

    /** Creates a new SetSessionProjectRequest instance. */
    constructor($$source: Partial<SetSessionProjectRequest> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SetSessionProjectRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SetSessionProjectRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SetSessionProjectRequest($$parsedSource as Partial<SetSessionProjectRequest>);
    }
}

export class SetSessionRootDirRequest {
    "sessionId": string;
    "rootDir": string;

    /** Creates a new SetSessionRootDirRequest instance. */
    constructor($$source: Partial<SetSessionRootDirRequest> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("rootDir" in $$source)) {
            this["rootDir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SetSessionRootDirRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SetSessionRootDirRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SetSessionRootDirRequest($$parsedSource as Partial<SetSessionRootDirRequest>);
    }
}

export class SplitPaneRequest {
    "sessionId": string;
    "windowId": string;
    "targetPaneId": string;
    "direction": string;
    "initialPty"?: StartPTYOptions | null;

    /** Creates a new SplitPaneRequest instance. */
    constructor($$source: Partial<SplitPaneRequest> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("windowId" in $$source)) {
            this["windowId"] = "";
        }
        if (!("targetPaneId" in $$source)) {
            this["targetPaneId"] = "";
        }
        if (!("direction" in $$source)) {
            this["direction"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SplitPaneRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SplitPaneRequest {
        const $$createField4_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("initialPty" in $$parsedSource) {
            $$parsedSource["initialPty"] = $$createField4_0($$parsedSource["initialPty"]);
        }
        return new SplitPaneRequest($$parsedSource as Partial<SplitPaneRequest>);
    }
}

export class SplitPaneResult {
    "session": session$0.Session;
    "paneId": string;
    "ptyId"?: string | null;
    "legacyPtyId"?: string;

    /** Creates a new SplitPaneResult instance. */
    constructor($$source: Partial<SplitPaneResult> = {}) {
        if (!("session" in $$source)) {
            this["session"] = (new session$0.Session());
        }
        if (!("paneId" in $$source)) {
            this["paneId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SplitPaneResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SplitPaneResult {
        const $$createField0_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        return new SplitPaneResult($$parsedSource as Partial<SplitPaneResult>);
    }
}

export class StartExecutionRequest {
    "workItemId": string;
    "sessionId"?: string;
    "ptyId"?: string;
    "launch"?: boolean;
    "agentProfileId"?: string;
    "systemPrompt"?: string;
    "actor"?: string;

    /** Creates a new StartExecutionRequest instance. */
    constructor($$source: Partial<StartExecutionRequest> = {}) {
        if (!("workItemId" in $$source)) {
            this["workItemId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartExecutionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): StartExecutionRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartExecutionRequest($$parsedSource as Partial<StartExecutionRequest>);
    }
}

export class StartHTTPForwardRequest {
    "name": string;
    "targetUrl": string;
    "sessionId": string;

    /** Creates a new StartHTTPForwardRequest instance. */
    constructor($$source: Partial<StartHTTPForwardRequest> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("targetUrl" in $$source)) {
            this["targetUrl"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartHTTPForwardRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): StartHTTPForwardRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartHTTPForwardRequest($$parsedSource as Partial<StartHTTPForwardRequest>);
    }
}

export class StartPTYAgentBridgeOptions {
    "enabled": boolean;
    "provider"?: string;

    /** Creates a new StartPTYAgentBridgeOptions instance. */
    constructor($$source: Partial<StartPTYAgentBridgeOptions> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartPTYAgentBridgeOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): StartPTYAgentBridgeOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartPTYAgentBridgeOptions($$parsedSource as Partial<StartPTYAgentBridgeOptions>);
    }
}

export class StartPTYOptions {
    "cols": number;
    "rows": number;
    "command"?: string;
    "env"?: { [_ in string]?: string };
    "args"?: string[];
    "exec"?: boolean;
    "agentBridge"?: StartPTYAgentBridgeOptions | null;

    /** Creates a new StartPTYOptions instance. */
    constructor($$source: Partial<StartPTYOptions> = {}) {
        if (!("cols" in $$source)) {
            this["cols"] = 0;
        }
        if (!("rows" in $$source)) {
            this["rows"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartPTYOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): StartPTYOptions {
        const $$createField3_0 = $$createType28;
        const $$createField4_0 = $$createType8;
        const $$createField6_0 = $$createType30;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("env" in $$parsedSource) {
            $$parsedSource["env"] = $$createField3_0($$parsedSource["env"]);
        }
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField4_0($$parsedSource["args"]);
        }
        if ("agentBridge" in $$parsedSource) {
            $$parsedSource["agentBridge"] = $$createField6_0($$parsedSource["agentBridge"]);
        }
        return new StartPTYOptions($$parsedSource as Partial<StartPTYOptions>);
    }
}

export class StartPanePTYRequest {
    "sessionId": string;
    "paneId": string;
    "options": StartPTYOptions;

    /** Creates a new StartPanePTYRequest instance. */
    constructor($$source: Partial<StartPanePTYRequest> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("paneId" in $$source)) {
            this["paneId"] = "";
        }
        if (!("options" in $$source)) {
            this["options"] = (new StartPTYOptions());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartPanePTYRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): StartPanePTYRequest {
        const $$createField2_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField2_0($$parsedSource["options"]);
        }
        return new StartPanePTYRequest($$parsedSource as Partial<StartPanePTYRequest>);
    }
}

export class StartPlanningRequest {
    "workItemId": string;
    "sessionId"?: string;
    "ptyId"?: string;
    "launch"?: boolean;
    "agentProfileId"?: string;
    "systemPrompt"?: string;
    "actor"?: string;

    /** Creates a new StartPlanningRequest instance. */
    constructor($$source: Partial<StartPlanningRequest> = {}) {
        if (!("workItemId" in $$source)) {
            this["workItemId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartPlanningRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): StartPlanningRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartPlanningRequest($$parsedSource as Partial<StartPlanningRequest>);
    }
}

export class StartWorkItemRunRequest {
    "workItemId": string;
    "preset"?: string;
    "promptTemplateId"?: string;
    "sessionId"?: string;
    "ptyId"?: string;
    "launch"?: boolean;
    "agentProfileId"?: string;
    "systemPrompt"?: string;
    "actor"?: string;

    /** Creates a new StartWorkItemRunRequest instance. */
    constructor($$source: Partial<StartWorkItemRunRequest> = {}) {
        if (!("workItemId" in $$source)) {
            this["workItemId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartWorkItemRunRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): StartWorkItemRunRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartWorkItemRunRequest($$parsedSource as Partial<StartWorkItemRunRequest>);
    }
}

export class StartedHTTPForward {
    "id": string;
    "localUrl": string;
    "forward": HTTPForward;

    /** Creates a new StartedHTTPForward instance. */
    constructor($$source: Partial<StartedHTTPForward> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("localUrl" in $$source)) {
            this["localUrl"] = "";
        }
        if (!("forward" in $$source)) {
            this["forward"] = (new HTTPForward());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartedHTTPForward instance from a string or object.
     */
    static createFrom($$source: any = {}): StartedHTTPForward {
        const $$createField2_0 = $$createType31;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("forward" in $$parsedSource) {
            $$parsedSource["forward"] = $$createField2_0($$parsedSource["forward"]);
        }
        return new StartedHTTPForward($$parsedSource as Partial<StartedHTTPForward>);
    }
}

export class StartedPanePTY {
    "session": session$0.Session;
    "ptyId": string;

    /** Creates a new StartedPanePTY instance. */
    constructor($$source: Partial<StartedPanePTY> = {}) {
        if (!("session" in $$source)) {
            this["session"] = (new session$0.Session());
        }
        if (!("ptyId" in $$source)) {
            this["ptyId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartedPanePTY instance from a string or object.
     */
    static createFrom($$source: any = {}): StartedPanePTY {
        const $$createField0_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        return new StartedPanePTY($$parsedSource as Partial<StartedPanePTY>);
    }
}

export const StatusEvent = workitem$0.StatusEvent;
export type StatusEvent = workitem$0.StatusEvent;

export class SubmitDraftPlanRequest {
    "workItemId": string;
    "runId"?: string;
    "title"?: string;
    "body": string;
    "actor"?: string;

    /** Creates a new SubmitDraftPlanRequest instance. */
    constructor($$source: Partial<SubmitDraftPlanRequest> = {}) {
        if (!("workItemId" in $$source)) {
            this["workItemId"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SubmitDraftPlanRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SubmitDraftPlanRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SubmitDraftPlanRequest($$parsedSource as Partial<SubmitDraftPlanRequest>);
    }
}

export class SubmitReviewFeedbackRequest {
    "workItemId": string;
    "runId"?: string;
    "body": string;
    "actor"?: string;

    /** Creates a new SubmitReviewFeedbackRequest instance. */
    constructor($$source: Partial<SubmitReviewFeedbackRequest> = {}) {
        if (!("workItemId" in $$source)) {
            this["workItemId"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SubmitReviewFeedbackRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SubmitReviewFeedbackRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SubmitReviewFeedbackRequest($$parsedSource as Partial<SubmitReviewFeedbackRequest>);
    }
}

export class UpdateProjectAttachmentRequest {
    "projectId": string;
    "title"?: string | null;
    "path"?: string | null;
    "url"?: string | null;
    "note"?: string | null;
    "provider"?: string | null;
    "target"?: string | null;
    "includeInContext"?: boolean | null;
    "meta"?: { [_ in string]?: MetadataValue };

    /** Creates a new UpdateProjectAttachmentRequest instance. */
    constructor($$source: Partial<UpdateProjectAttachmentRequest> = {}) {
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateProjectAttachmentRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateProjectAttachmentRequest {
        const $$createField8_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("meta" in $$parsedSource) {
            $$parsedSource["meta"] = $$createField8_0($$parsedSource["meta"]);
        }
        return new UpdateProjectAttachmentRequest($$parsedSource as Partial<UpdateProjectAttachmentRequest>);
    }
}

export class UpdateProjectRequest {
    "name"?: string | null;
    "description"?: string | null;
    "slug"?: string | null;

    /** Creates a new UpdateProjectRequest instance. */
    constructor($$source: Partial<UpdateProjectRequest> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateProjectRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateProjectRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateProjectRequest($$parsedSource as Partial<UpdateProjectRequest>);
    }
}

export const WorkItem = workitem$0.WorkItem;
export type WorkItem = workitem$0.WorkItem;

export const WorkItemRun = workitem$0.WorkItemRun;
export type WorkItemRun = workitem$0.WorkItemRun;

export const WorkflowEvent = workitem$0.WorkflowEvent;
export type WorkflowEvent = workitem$0.WorkflowEvent;

export const WorkflowTemplate = workitem$0.WorkflowTemplate;
export type WorkflowTemplate = workitem$0.WorkflowTemplate;

export class Worktree {
    "branch": string;
    "path": string;
    "kind": string;
    "isMain": boolean;
    "isCurrent": boolean;
    "dirty": boolean;
    "locked": boolean;

    /** Creates a new Worktree instance. */
    constructor($$source: Partial<Worktree> = {}) {
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("isMain" in $$source)) {
            this["isMain"] = false;
        }
        if (!("isCurrent" in $$source)) {
            this["isCurrent"] = false;
        }
        if (!("dirty" in $$source)) {
            this["dirty"] = false;
        }
        if (!("locked" in $$source)) {
            this["locked"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Worktree instance from a string or object.
     */
    static createFrom($$source: any = {}): Worktree {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Worktree($$parsedSource as Partial<Worktree>);
    }
}

export class WorktrunkBinary {
    "path": string;
    "version": string;

    /** Creates a new WorktrunkBinary instance. */
    constructor($$source: Partial<WorktrunkBinary> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorktrunkBinary instance from a string or object.
     */
    static createFrom($$source: any = {}): WorktrunkBinary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorktrunkBinary($$parsedSource as Partial<WorktrunkBinary>);
    }
}

export class WorktrunkStatus {
    "available": boolean;
    "configFound": boolean;
    "binary": WorktrunkBinary;

    /** Creates a new WorktrunkStatus instance. */
    constructor($$source: Partial<WorktrunkStatus> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("configFound" in $$source)) {
            this["configFound"] = false;
        }
        if (!("binary" in $$source)) {
            this["binary"] = (new WorktrunkBinary());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorktrunkStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): WorktrunkStatus {
        const $$createField2_0 = $$createType32;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("binary" in $$parsedSource) {
            $$parsedSource["binary"] = $$createField2_0($$parsedSource["binary"]);
        }
        return new WorktrunkStatus($$parsedSource as Partial<WorktrunkStatus>);
    }
}

export class WritePTYRequest {
    "ptyId": string;
    "data": string;

    /** Creates a new WritePTYRequest instance. */
    constructor($$source: Partial<WritePTYRequest> = {}) {
        if (!("ptyId" in $$source)) {
            this["ptyId"] = "";
        }
        if (!("data" in $$source)) {
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WritePTYRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): WritePTYRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WritePTYRequest($$parsedSource as Partial<WritePTYRequest>);
    }
}

// Private type creation functions
const $$createType0 = workitem$0.MetadataValue.createFrom;
const $$createType1 = $Create.Map($Create.Any, $$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = AgentBridgeHookDecision.createFrom;
const $$createType4 = workitem$0.ProjectPreferences.createFrom;
const $$createType5 = StartPTYOptions.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = session$0.Session.createFrom;
const $$createType8 = $Create.Array($Create.Any);
const $$createType9 = onboarding$0.Item.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = PluginResolver.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = ProjectAttachmentTemplate.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = PluginTemplateField.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = ProjectContextItem.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = workitem$0.Project.createFrom;
const $$createType20 = workitem$0.WorkItem.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = $Create.Array($$createType7);
const $$createType23 = workitem$0.WorkItemRun.createFrom;
const $$createType24 = $Create.Array($$createType23);
const $$createType25 = workitem$0.StatusEvent.createFrom;
const $$createType26 = $Create.Nullable($$createType23);
const $$createType27 = $Create.Nullable($$createType20);
const $$createType28 = $Create.Map($Create.Any, $Create.Any);
const $$createType29 = StartPTYAgentBridgeOptions.createFrom;
const $$createType30 = $Create.Nullable($$createType29);
const $$createType31 = HTTPForward.createFrom;
const $$createType32 = WorktrunkBinary.createFrom;
